Add "Enrich Domain with OSINT from Slack"
rapid7/insightconnect-workflows pull request #288
Opened 2020-08-23 14:40 UTC by PhilippBehmer

WWF "Enrich Domain with OSINT from Slack"

2020-08-25 19:43 UTC, jmcadams-r7 commented on workflows/Enrich_Domain_with_OSINT_from_Slack/help.md
> +Import the workflow from the Rapid7 Extension Library and proceed through the Import Workflow wizard in InsightConnect. Import plugins, create or select connections, and rename the workflow as a part
Need instructions on configuring Slack

2020-08-25 19:46 UTC, jmcadams-r7 commented on workflows/Enrich_Domain_with_OSINT_from_Slack/Enrich_Domain_with_OSINT_from_Slack.icon
> +            "continueOnFailure": false,
You'll need to set continueOnFailure to True, and/or add error messages in the flow. If the WF bombs out, we want the user to see that in slack with a link back to the failed job.

2021-01-22 15:00 UTC, PhilippBehmer commented on workflows/Enrich_Domain_with_OSINT_from_Slack/Enrich_Domain_with_OSINT_from_Slack.icon
> +            "continueOnFailure": false,
@jmcadams-r7 I implemented a check if one of the steps fails and ICON will send a Slack msg including the job url in case of a step failure.



Not

2021-01-22 15:06 UTC, PhilippBehmer commented on workflows/Enrich_Domain_with_OSINT_from_Slack/help.md
> +Import the workflow from the Rapid7 Extension Library and proceed through the Import Workflow wizard in InsightConnect. Import plugins, create or select connections, and rename the workflow as a part
I added a link to our Slack App documentation and a description on how to change from direct msg to channel listener

2021-01-22 15:09 UTC, PhilippBehmer commented
I implemented your change requests, updated the plugins, and also use cloud plugins now which run MUCH faster 🚀 

@jmcadams-r7 & @sengleson-r7 can you please review?

2021-01-22 15:27 UTC, sengleson-r7 requested changes
I just imported and ran this, it was done before I could even open the thread! Awesome work Phil! One really small typo in the key features =)

2021-01-22 15:27 UTC, sengleson-r7 commented on workflows/Enrich_Domain_with_OSINT_from_Slack/help.md
> +* ThreadCrowd URL Lookup
```suggestion
* Threat Crowd URL Lookup
```

2021-01-22 15:33 UTC, PhilippBehmer commented on workflows/Enrich_Domain_with_OSINT_from_Slack/help.md
> +* ThreadCrowd URL Lookup
Thank you! Fixed!

2021-01-22 15:34 UTC, sengleson-r7 approved these changes

2021-01-22 15:36 UTC, sengleson-r7 requested changes
Sorry Phil! I just realized, this would be a cloud enabled workflow -- zero deployment required!!

2021-01-22 15:36 UTC, sengleson-r7 commented on workflows/Enrich_Domain_with_OSINT_from_Slack/workflow.spec.yaml
> +  keywords: [slack, chat, chatops, work_from_home]
```suggestion
  keywords: [slack, chat, chatops, work_from_home, cloud_enabled]
```

2021-01-22 15:39 UTC, sengleson-r7 approved these changes

2021-01-22 15:41 UTC, jschipp-r7 approved these changes

2021-01-22 15:41 UTC, merged

2021-01-22 15:42 UTC, jschipp-r7 commented
Successfully validated

```
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 28.357ms
```

2021-01-22 15:44 UTC, PhilippBehmer commented on workflows/Enrich_Domain_with_OSINT_from_Slack/workflow.spec.yaml
> +  keywords: [slack, chat, chatops, work_from_home]
yep! Thanks for adding the tag!