Add "Forward Alerts from InsightIDR to Slack"
rapid7/insightconnect-workflows pull request #290
Opened 2020-08-23 20:09 UTC by PhilippBehmer

WWF "Forward Alerts from InsightIDR to Slack"

2020-08-25 19:40 UTC, jmcadams-r7 commented on workflows/Forward_Alerts_from_InsightIDR_to_Slack/Forward_Alerts_from_InsightIDR_to_Slack.icon
> +        "description": "",
Need WF description

2020-08-25 19:41 UTC, jmcadams-r7 commented on workflows/Forward_Alerts_from_InsightIDR_to_Slack/help.md
> +Import the workflow from the Rapid7 Extension Library and proceed through the Import Workflow wizard in InsightConnect. Import plugins, create or select connections, and rename the workflow as a part
There should be a line in here about configuring your slack channel.

2020-09-15 23:19 UTC, jschipp-r7 commented on workflows/Forward_Alerts_from_InsightIDR_to_Slack/help.md
> +After import, activate the workflow in order to trigger it.
```suggestion
Once the workflow has been imported, **update the first step with the channel name to suit your Slack environment** by editing the input with the preset text of `change_me` to match the channel to monitor.
```

2020-09-15 23:19 UTC, jschipp-r7 commented on workflows/Forward_Alerts_from_InsightIDR_to_Slack/help.md
> +Import the workflow from the Rapid7 Extension Library and proceed through the Import Workflow wizard in InsightConnect. Import plugins, create or select connections, and rename the workflow as a part
Added

2020-09-15 23:20 UTC, jschipp-r7 commented on workflows/Forward_Alerts_from_InsightIDR_to_Slack/help.md
> +You can also manually trigger this workflow from the investigation. To do this click the `Take Action` button and choose `Custom InsightConnect Workflows`. From the list select the imported workflow.
```suggestion
You can also manually trigger this workflow from the investigation. To do this click the **Take Action** button and choose **Custom InsightConnect Workflows**. From the list select the imported workflow.
```

2020-09-15 23:22 UTC, jschipp-r7 commented on workflows/Forward_Alerts_from_InsightIDR_to_Slack/Forward_Alerts_from_InsightIDR_to_Slack.icon
> +                "recipient": "#secops",
This should be `change_me` per convention, not hardcoded channel. Update title of step too

2020-09-15 23:22 UTC, jschipp-r7 commented on workflows/Forward_Alerts_from_InsightIDR_to_Slack/help.md
> +Import the workflow from the Rapid7 Extension Library and proceed through the Import Workflow wizard in InsightConnect. Import plugins, create or select connections, and rename the workflow as a part
This is done after this section

2020-09-15 23:22 UTC, jschipp-r7 commented on workflows/Forward_Alerts_from_InsightIDR_to_Slack/help.md
> +Once the workflow has been imported, **update the first step with the channel name to suit your Slack environment** by editing the input with the preset text of `change_me` to match the channel to mo
```suggestion
Once the workflow has been imported, **update the Slack step with the channel name to suit your Slack environment** by editing the input with the preset text of `change_me` to match the channel to monitor.
```

2021-01-22 15:40 UTC, PhilippBehmer commented on workflows/Forward_Alerts_from_InsightIDR_to_Slack/Forward_Alerts_from_InsightIDR_to_Slack.icon
> +        "description": "",
added ✅

2021-01-22 15:41 UTC, PhilippBehmer commented on workflows/Forward_Alerts_from_InsightIDR_to_Slack/help.md
> +Import the workflow from the Rapid7 Extension Library and proceed through the Import Workflow wizard in InsightConnect. Import plugins, create or select connections, and rename the workflow as a part
Thanks @jschipp-r7

2021-01-22 15:41 UTC, PhilippBehmer commented on workflows/Forward_Alerts_from_InsightIDR_to_Slack/Forward_Alerts_from_InsightIDR_to_Slack.icon
> +                "recipient": "#secops",
I updated the channel name and step title

2021-01-22 15:42 UTC, PhilippBehmer commented
I implemented the changes. Please review.
@jschipp-r7 @jmcadams-r7 @sengleson-r7

2021-01-23 11:43 UTC, PhilippBehmer commented
I can't validate this one as the validator crashes if there are no plugin steps

❯ icon-validate ./Forward_Alerts_from_InsightIDR_to_Slack
[*] Validating workflow at ./Forward_Alerts_from_InsightIDR_to_Slack

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
Traceback (most recent call last):
  File "/usr/local/bin/icon-validate", line 8, in <module>
    sys.exit(main())
  File "/Library/Python/3.7/site-packages/icon_validator/__main__.py", line 52, in main
    validate(directory=path, spec_file_name=spec_file_name)
  File "/Library/Python/3.7/site-packages/icon_validator/validate.py", line 35, in validate
    v.validate(spec)
  File "/Library/Python/3.7/site-packages/icon_validator/rules/workflow_validators/workflow_help_plugin_utilization_validator.py", line 119, in validate
    plugin_in_help = WorkflowHelpPluginUtilizationValidator.extract_plugins_in_help(spec.raw_help())
  File "/Library/Python/3.7/site-packages/icon_validator/rules/workflow_validators/workflow_help_plugin_utilization_validator.py", line 102, in extract_plugins_in_help
    plugins_list = plugins_utilized[0].split("\n")
IndexError: list index out of range

2021-01-26 15:26 UTC, ncramer-r7 requested changes

2021-01-26 15:26 UTC, ncramer-r7 commented on workflows/Forward_Alerts_from_InsightIDR_to_Slack/help.md
> +By default this workflow forwards the IDR Alerts to the Slack channel `#secops`. This can be changed in the last workflow step.
```suggestion
By default this workflow forwards the IDR Alerts to the Slack channel `#change_me`. This can be changed in the last workflow step.
```

I think the reference to #secops is in the workflow description as well

2021-01-26 15:29 UTC, ncramer-r7 commented on workflows/Forward_Alerts_from_InsightIDR_to_Slack/workflow.spec.yaml
> +description: This workflow forwards IDR alerts to a Slack channel.
```suggestion
description: This workflow forwards IDR alerts to a Slack channel
```

2021-02-02 23:47 UTC, jschipp-r7 approved these changes

2021-02-02 23:47 UTC, merged