[SOAR-2436] - Delete_Assets_with_InsightVM_from_Slack
rapid7/insightconnect-workflows pull request #311
Opened 2020-09-02 21:03 UTC by jmcadams-r7

## Requirements

This PR adds the Delete_Assets_with_InsightVM_from_Slack workflow

## Validation: 
```
rmt-mbp-5357:Delete_Assets_with_InsightVM_from_Slack jmcadams$ icon-validate .
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!
```

## Screenshots: 
![slack_flow1](https://user-images.githubusercontent.com/44783688/92036464-e3da3700-ed35-11ea-975d-12ca259970f9.png)
![workflow1](https://user-images.githubusercontent.com/44783688/92036466-e472cd80-ed35-11ea-93dd-68fb54a26b5c.png)
![workflow2](https://user-images.githubusercontent.com/44783688/92036468-e472cd80-ed35-11ea-9dc3-2e840a2763aa.png)

2020-09-02 21:11 UTC, mrinehart-r7 requested changes

2020-09-02 21:11 UTC, mrinehart-r7 commented on workflows/Delete_Assets_with_InsightVM_from_Slack/help.md
> +Delete assets from InsightVM using a command from Slack
```suggestion
Delete assets from InsightVM using a command from Slack.
```

2020-09-02 21:11 UTC, mrinehart-r7 commented on workflows/Delete_Assets_with_InsightVM_from_Slack/help.md
> +`delete-asset 12345`
```suggestion
`@Rapid7 InsightConnect delete-asset 12345`
```

2020-09-02 21:11 UTC, mrinehart-r7 commented on workflows/Delete_Assets_with_InsightVM_from_Slack/help.md
> +`delete-asset 12345 123456`
```suggestion
`@Rapid7 InsightConnect delete-asset 12345 123456`
```

2020-09-03 14:09 UTC, ncramer-r7 commented on workflows/Delete_Assets_with_InsightVM_from_Slack/Delete_Assets_with_InsightVM_from_Slack.icon
> +          "matchChannel": "integration-testing",
```suggestion
          "matchChannel": "change_me",
```

2020-09-03 14:14 UTC, ncramer-r7 requested changes

2020-09-03 14:14 UTC, ncramer-r7 commented on workflows/Delete_Assets_with_InsightVM_from_Slack/Delete_Assets_with_InsightVM_from_Slack.icon
> +          "matchChannel": "integration-testing",
```suggestion
          "matchChannel": "change_me",
```

2020-09-03 14:54 UTC, ncramer-r7 approved these changes

2020-09-03 16:57 UTC, mrinehart-r7 approved these changes

2020-09-03 16:57 UTC, merged