SOAR_2527_Update_OSINT_Indicator_Enrichment_with_Slack
rapid7/insightconnect-workflows pull request #312
Opened 2020-09-03 14:05 UTC by ekim-r7

### Proposed Changes

- Update workflow to use loop outputs
- Rename Open_Source_Indicator_Enrichment_with_Slack

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<img width="167" alt="workflow1" src="https://user-images.githubusercontent.com/69210907/92124622-0159e000-edcc-11ea-834a-1ec6ff8926e4.png">
<img width="187" alt="workflow2" src="https://user-images.githubusercontent.com/69210907/92124583-f43cf100-edcb-11ea-9197-c7e27e4f1641.png">
<img width="183" alt="workflow3" src="https://user-images.githubusercontent.com/69210907/92124584-f43cf100-edcb-11ea-8cad-b34f0c53f417.png">
<img width="182" alt="workflow4" src="https://user-images.githubusercontent.com/69210907/92124587-f43cf100-edcb-11ea-881c-f42873ea584a.png">

#### Job

<img width="388" alt="slack1" src="https://user-images.githubusercontent.com/69210907/92124861-4bdb5c80-edcc-11ea-9386-6cdfa5291c7a.png">
<img width="392" alt="slack2" src="https://user-images.githubusercontent.com/69210907/92124878-4e3db680-edcc-11ea-9ad7-5229c1bc2bc7.png">
<img width="374" alt="slack3" src="https://user-images.githubusercontent.com/69210907/92124881-4f6ee380-edcc-11ea-8fa6-41ff1ebbe373.png">

#### Artifact

<img width="873" alt="artifact1" src="https://user-images.githubusercontent.com/69210907/92124549-e9825c00-edcb-11ea-8f04-d8a72ba58a16.png">
<img width="867" alt="artifact2" src="https://user-images.githubusercontent.com/69210907/92124555-eb4c1f80-edcb-11ea-989b-14f27036e2e6.png">
<img width="871" alt="artifact3" src="https://user-images.githubusercontent.com/69210907/92124558-ebe4b600-edcb-11ea-9c6a-297ff0277c84.png">

### Validation
ekim@BOS-MBP-8175:~/go/src/github.com/rapid7/insightconnect-workflows/workflows/Open_Source_Indicator_Enrichment_with_Slack|SOAR_2527_Update_OSINT_Indicator_Enrichment_with_Slack⚡ ⇒  icon-validate .
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 29.769000000000002ms

2020-09-03 14:29 UTC, mhofert-r7 submitted a review, later dismissed

2020-09-03 14:54 UTC, ncramer-r7 requested changes
can't make the specific line edit, but be sure to include a value for humanCostSeconds on line 1676

2020-09-03 17:12 UTC, mrinehart-r7 commented
@ekim-r7 I think the ability to handle an invalid command may have gotten lost in the update - maybe check if all of the indicators are empty, and if so, send an invalid command message to the user?

2020-09-03 17:13 UTC, mrinehart-r7 requested changes

2020-09-03 17:13 UTC, mrinehart-r7 commented on workflows/Enrich_Indicators_with_OSINT_from_Slack/Enrich_Indicators_with_OSINT_from_Slack.icon
>  {
I think the 'invalid command' logic was lost in the update - see my comment on the main thread of this PR

2020-09-04 19:17 UTC, mrinehart-r7 approved these changes

2020-09-04 19:56 UTC, merged