Update Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Slack with indicator extraction
rapid7/insightconnect-workflows pull request #315
Opened 2020-09-04 14:25 UTC by ncramer-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<img width="329" alt="workflow" src="https://user-images.githubusercontent.com/69209594/92249936-d25d7000-ee98-11ea-99bd-3f3e46ac9dfb.png">

<img width="279" alt="workflow_loop" src="https://user-images.githubusercontent.com/69209594/92249967-d7baba80-ee98-11ea-9d51-844238fa23e7.png">

#### Job

<img width="576" alt="slack_found" src="https://user-images.githubusercontent.com/69209594/92249981-de493200-ee98-11ea-8611-85ce6984d853.png">

<img width="580" alt="slack_notfound" src="https://user-images.githubusercontent.com/69209594/92249994-e1dcb900-ee98-11ea-83b5-b63a3c1a34e1.png">

#### Artifact

<img width="1180" alt="artifact" src="https://user-images.githubusercontent.com/69209594/92250009-e6a16d00-ee98-11ea-9389-5477508f87d1.png">

##Validation

```
ncramer@BOS-MBP-8176:~/go/src/github.com/rapid7/insightconnect-workflows/workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Slack|update-palo-alto-slack-check-status⚡ ⇒  icon-validate .
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 29.590999999999998ms
```

2020-09-04 14:55 UTC, jmcadams-r7 approved these changes

2020-09-17 18:54 UTC, jmcadams-r7 submitted a review, later dismissed

2020-09-17 18:56 UTC, mrinehart-r7 requested changes

2020-09-17 18:56 UTC, mrinehart-r7 commented on workflows/Check_Host_Block_Status_with_Palo_Alto_Firewall_from_Slack/help.md
> +* The ability to see if an IP or domain is currently blocked by the firewall
```suggestion
* The ability to see if an IP address or domain is currently blocked by the firewall
```

2020-09-17 18:56 UTC, merged