Update Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams with indicator extraction
rapid7/insightconnect-workflows pull request #319
Opened 2020-09-04 19:36 UTC by ncramer-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<img width="355" alt="workflow" src="https://user-images.githubusercontent.com/69209594/92278928-377a8b00-eec4-11ea-9224-b6c1d64d48fc.png">

<img width="333" alt="workflow_loop" src="https://user-images.githubusercontent.com/69209594/92278931-39dce500-eec4-11ea-8d90-a86f8fc22298.png">

#### Job

<img width="1010" alt="teams_block_success" src="https://user-images.githubusercontent.com/69209594/92278944-3e090280-eec4-11ea-9fd5-835625662767.png">

<img width="1009" alt="teams_unblock_success" src="https://user-images.githubusercontent.com/69209594/92278950-406b5c80-eec4-11ea-8764-023469a98fbf.png">

<img width="994" alt="teams_unblock_failure" src="https://user-images.githubusercontent.com/69209594/92278967-47926a80-eec4-11ea-9966-44321a70c1af.png">

#### Artifact

<img width="1189" alt="artifact" src="https://user-images.githubusercontent.com/69209594/92278982-4f520f00-eec4-11ea-86e8-8d4b559a0d6f.png">

## Validation

```
ncramer@BOS-MBP-8176:~/go/src/github.com/rapid7/insightconnect-workflows/workflows/Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams|update-palo-alto-microsoft_teams-block-host⚡ ⇒  icon-validate .
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 27.063ms
```

2020-09-04 19:40 UTC, mrinehart-r7 requested changes

2020-09-04 19:40 UTC, mrinehart-r7 commented on workflows/Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams/Block_Host_with_Palo_Alto_Firewall_from_Microsoft_Teams.icon
> +                "message_content": "✅<b>Block Host Success</b> ✅<br>\n<br>\nBlocked: <code>{{[634ba1d9-2e69-4adf-b15b-1c32b1559e4c].[$item]}}</code>",
```suggestion
                "message_content": "✅ <b>Block Host Success</b> ✅<br>\n<br>\nBlocked: <code>{{[634ba1d9-2e69-4adf-b15b-1c32b1559e4c].[$item]}}</code>",
```

2020-09-04 19:40 UTC, mrinehart-r7 approved these changes

2020-09-17 18:52 UTC, jmcadams-r7 approved these changes

2020-09-17 18:53 UTC, merged