Enrich Malicious Hash Alerts from InsightIDR with OSINT
rapid7/insightconnect-workflows pull request #321
Opened 2020-09-10 12:45 UTC by PhilippBehmer

WWF

2020-09-10 16:59 UTC, sengleson-r7 requested changes

2020-09-10 16:59 UTC, sengleson-r7 commented on workflows/Enrich_Malicious_Hash_Alerts_from_InsightIDR_with_OSINT/help.md
> +* ThreadCrowd Lookup
```suggestion
* Threat Crowd Lookup
```

2021-01-22 16:28 UTC, PhilippBehmer commented
fixed typo and changed the plugins to cloud plugins.
@sengleson-r7  please review

2021-01-23 11:48 UTC, PhilippBehmer commented
❯ icon-validate Enrich_Malicious_Hash_Alerts_from_InsightIDR_with_OSINT
[*] Validating workflow at Enrich_Malicious_Hash_Alerts_from_InsightIDR_with_OSINT

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 18.154ms

2021-01-26 16:06 UTC, ncramer-r7 approved these changes

2021-02-02 23:40 UTC, jschipp-r7 approved these changes

2021-02-02 23:41 UTC, jschipp-r7 approved these changes

2021-02-02 23:42 UTC, merged