Add "Add Asset Criticality Tag in InsightVM from Slack"
rapid7/insightconnect-workflows pull request #323
Opened 2020-09-10 14:36 UTC by PhilippBehmer

WWF

2020-09-15 23:14 UTC, jschipp-r7 commented on workflows/Add_Asset_Criticality_Tag_in_InsightVM_from_Slack/workflow.spec.yaml
> +description: Set criticality tag from slack with interactive slack message.
```suggestion
description: Set criticality tag from Slack with interactive slack message.
```

2020-09-15 23:16 UTC, jschipp-r7 requested changes
Can we change `in` references to `with` to match the other workflows?

<Verb> with <Product> from <Chat Tool>

2020-09-16 14:44 UTC, lmilby-r7 commented on workflows/Add_Asset_Criticality_Tag_in_InsightVM_from_Slack/help.md
> +Set criticality tag from Slack with interactive Slack message.
```suggestion
Sets criticality tag from Slack with an interactive Slack message.
```

2020-09-16 14:44 UTC, lmilby-r7 commented on workflows/Add_Asset_Criticality_Tag_in_InsightVM_from_Slack/help.md
> +After import, activate the workflow in order to trigger it.
```suggestion
After the workflow has been import, activate the it in order to enable the ability to trigger it.
```

2020-09-16 14:44 UTC, lmilby-r7 commented on workflows/Add_Asset_Criticality_Tag_in_InsightVM_from_Slack/help.md
> +To run the workflow, send a direct message to your InsightConnect Slack Chatbot or @ your Chatbot in a public channel starting with the command `crit-tag-asset`.
```suggestion
To trigger the workflow, send a direct message to your InsightConnect Slack Chatbot or @ your Chatbot in a public channel starting with the command `crit-tag-asset`.
```

2021-01-22 20:18 UTC, PhilippBehmer commented
- Applied your changes
- Changed WF name from in to with
- Plugins updated and cloud plugins used
- Switch from extract plugin to Slack "words" output
- Remove filter step, use the timeout path
- New screenshots

@jonschipp @sengleson-r7 please review

2021-01-22 21:58 UTC, jschipp-r7 commented on workflows/Add_Asset_Criticality_Tag_with_InsightVM_from_Slack/workflow.spec.yaml
> +  source_url: https://github.com/rapid7/insightconnect-workflows/tree/master/workflows/Add_Asset_Criticality_Tag_in_InsightVM_from_Slack
```suggestion
  source_url: https://github.com/rapid7/insightconnect-workflows/tree/master/workflows/Add_Asset_Criticality_Tag_with_InsightVM_from_Slack
```

2021-01-22 21:59 UTC, jschipp-r7 approved these changes

2021-01-22 21:59 UTC, merged