Create Manage_Hosts_with_Darktrace_from_Slack workflow
rapid7/insightconnect-workflows pull request #331
Opened 2020-09-21 16:33 UTC by ncramer-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

![workflow](https://user-images.githubusercontent.com/69209594/93794172-c2b68900-fc05-11ea-9700-4bba6521c777.png)

![workflow_loop](https://user-images.githubusercontent.com/69209594/93794176-c518e300-fc05-11ea-8784-1237ceb50342.png)

#### Job

<img width="581" alt="slack_add_success" src="https://user-images.githubusercontent.com/69209594/93794215-cf3ae180-fc05-11ea-99e7-5e62eea7df15.png">
<img width="572" alt="slack_remove_success" src="https://user-images.githubusercontent.com/69209594/93794219-cfd37800-fc05-11ea-879a-ee6d4df9bd7b.png">
<img width="582" alt="slack_failure" src="https://user-images.githubusercontent.com/69209594/93794217-cfd37800-fc05-11ea-9099-8e743da87b08.png">

#### Artifact

![artifact](https://user-images.githubusercontent.com/69209594/93794573-3c4e7700-fc06-11ea-8d73-b5b9f5a3c7b6.png)

## Validation
```
ncramer@BOS-MBP-8176:~/go/src/github.com/rapid7/insightconnect-workflows/workflows/Manage_Hosts_with_Darktrace_from_Slack|darktrace-slack-workflow ⇒  icon-validate .
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 19.282ms
```

2020-09-21 16:36 UTC, ncramer-r7 commented
Darktrace may need a new plugin icon -- currently it is hard to see in the product since it is black.

2020-09-21 18:33 UTC, jschipp-r7 requested changes
Waiting to hear back from Darktrace on whether Domains are only supported. If so, we will need to update all the naming and language.

2020-09-22 16:36 UTC, jschipp-r7 requested changes

2020-09-22 16:36 UTC, jschipp-r7 commented on workflows/Manage_Hosts_with_Darktrace_from_Slack/workflow.spec.yaml
> +title: Manage Hosts with Darktrace from Slack
```suggestion
title: Manage Watched Domains with Darktrace from Slack
```

2020-09-22 16:36 UTC, jschipp-r7 commented on workflows/Manage_Hosts_with_Darktrace_from_Slack/workflow.spec.yaml
> +name: Manage_Hosts_with_Darktrace_from_Slack
```suggestion
name: Manage_Watched_Domains_with_Darktrace_from_Slack
```

2020-09-22 16:36 UTC, jschipp-r7 commented on workflows/Manage_Hosts_with_Darktrace_from_Slack/workflow.spec.yaml
> +description: Add or remove hosts in the Darktrace watched domains list from Slack.
```suggestion
description: Add or remove domains and IP addresses in the Darktrace watched domains list from Slack.
```

2020-09-22 16:36 UTC, jschipp-r7 commented on workflows/Manage_Hosts_with_Darktrace_from_Slack/workflow.spec.yaml
> +  keywords: [chat, chatops, edr, endpoint, darktrace, work_from_home, slack]
```suggestion
  keywords: [chat, chatops, darktrace, nta, nsm, work_from_home, slack]
```

2020-09-22 19:19 UTC, jschipp-r7 approved these changes

2020-09-22 19:19 UTC, merged