Updated Hello IDR Alert Workflow
rapid7/insightconnect-workflows pull request #332
Opened 2020-09-21 19:26 UTC by sengleson-r7

Updated artifact, description, version bump

2020-09-21 22:20 UTC, zyoutz-r7 approved these changes

2020-09-22 15:07 UTC, ncramer-r7 approved these changes

2020-09-22 15:08 UTC, ncramer-r7 requested changes
Add a quick note about version log in help.md

2020-09-23 14:41 UTC, zyoutz-r7 approved these changes

2020-09-23 15:15 UTC, ncramer-r7 approved these changes

2020-09-23 16:43 UTC, merged