SOAR_2629_Update_Lookup_Vulnerability_From_Slack
rapid7/insightconnect-workflows pull request #337
Opened 2020-09-23 17:42 UTC by ekim-r7

## Description
- Update the workflow to work in the cloud
- Change directory name from _Lookup_Vuln_From_Slack_ to _Lookup_Vulnerability_From_Slack_ to match what is shown in the InsightConnect library

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<img width="256" alt="workflow" src="https://user-images.githubusercontent.com/69210907/94048770-00501900-fda2-11ea-8d15-b01297f06b48.png">
<img width="358" alt="workflow2" src="https://user-images.githubusercontent.com/69210907/94048792-05ad6380-fda2-11ea-8e63-44c5120db797.png">

#### Job

<img width="761" alt="execution1" src="https://user-images.githubusercontent.com/69210907/94048829-12ca5280-fda2-11ea-8328-c521e27aa503.png">
<img width="534" alt="execution2" src="https://user-images.githubusercontent.com/69210907/94048834-14941600-fda2-11ea-84d6-4623e28cd2cb.png">
<img width="1164" alt="job" src="https://user-images.githubusercontent.com/69210907/94048838-15c54300-fda2-11ea-9e23-cc6e3bea6ab1.png">

#### Artifact

<img width="992" alt="artifact1" src="https://user-images.githubusercontent.com/69210907/94048812-0c3bdb00-fda2-11ea-9de1-1bf4d7b49719.png">

```
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 31.014ms
```

2020-09-23 20:31 UTC, jschipp-r7 requested changes

2020-09-23 20:31 UTC, jschipp-r7 commented on workflows/Lookup_Vuln_From_Slack/workflow.spec.yaml
> +  source_url: https://github.com/rapid7/insightconnect-workflows/tree/master/workflows/Lookup_Vulnerability_From_Slack
This needs to be reverted
```suggestion
  source_url: https://github.com/rapid7/insightconnect-workflows/tree/master/workflows/Lookup_Vuln_From_Slack
```

2020-09-23 20:39 UTC, jschipp-r7 requested changes
The workflow is not consistent on whether the user should use `lookup-vuln` or `lookup_vuln` as the chat command. We use the hyphen `-` syntax in workflow commands because they're more similar to how people write English e.g. "ex-president" “self-expression,” “all-knowing". Will need to update all those references too

2020-09-24 21:17 UTC, mrinehart-r7 requested changes
Need to address Jon's comment before we can merge

2020-09-25 15:49 UTC, mrinehart-r7 commented on workflows/Lookup_Vuln_From_Slack/Lookup_Vuln_From_Slack.icon
> +            "name": "lookup-vulnerability Trigger",
```suggestion
            "name": "lookup-vuln Trigger",
```

2020-09-25 15:49 UTC, mrinehart-r7 commented on workflows/Lookup_Vuln_From_Slack/Lookup_Vuln_From_Slack.icon
> +                "matchText": "lookup-vulnerability",
```suggestion
                "matchText": "lookup-vuln",
```

2020-09-25 15:51 UTC, mrinehart-r7 commented on workflows/Lookup_Vuln_From_Slack/Lookup_Vuln_From_Slack.icon
> +        "name": "lookup-vulnerability Trigger",
```suggestion
        "name": "lookup-vuln Trigger",
```

2020-09-25 15:54 UTC, mrinehart-r7 requested changes
Left comments for the spots that need to be updated - I'd recommend doing the updates in the workflow builder to play it safe. The following screenshots also need to be updated aftewards: execution1.png, execution2.png, workflow.png

2020-09-25 15:54 UTC, mrinehart-r7 commented on workflows/Lookup_Vuln_From_Slack/Lookup_Vuln_From_Slack.icon
> +        "description": "Trigger this workflow by entering a Slack command in the following format:\n\"@Rapid7 InsightConnect lookup-vulnerability CVE-XXXX-XXXX\"\nOR\n\"@Rapid7 InsightConnect lookup-
```suggestion
        "description": "Trigger this workflow by entering a Slack command in the following format:\n\"@Rapid7 InsightConnect lookup-vuln CVE-XXXX-XXXX\"\nOR\n\"@Rapid7 InsightConnect lookup-vuln heartbleed\"",
```

2020-09-25 15:54 UTC, mrinehart-r7 commented on workflows/Lookup_Vuln_From_Slack/Lookup_Vuln_From_Slack.icon
> +          "matchText": "lookup-vulnerability",
```suggestion
          "matchText": "lookup-vuln",
```

2020-09-25 15:54 UTC, mrinehart-r7 commented on workflows/Lookup_Vuln_From_Slack/help.md
> +To run the workflow, send a direct message to your InsightConnect Slack Chatbot or @ your Chatbot in a public channel starting with the command `lookup-vulnerability`.
```suggestion
To run the workflow, send a direct message to your InsightConnect Slack Chatbot or @ your Chatbot in a public channel starting with the command `lookup-vuln`.
```

2020-09-25 15:54 UTC, mrinehart-r7 commented on workflows/Lookup_Vuln_From_Slack/help.md
> +* `lookup-vulnerability CVE-2020-0674`
```suggestion
* `lookup-vuln CVE-2020-0674`
```

2020-09-25 15:54 UTC, mrinehart-r7 commented on workflows/Lookup_Vuln_From_Slack/help.md
> +* `@Rapid7 InsightConnect lookup-vulnerability bluekeep`
```suggestion
* `@Rapid7 InsightConnect lookup-vuln bluekeep`
```

2020-09-25 20:47 UTC, mrinehart-r7 requested changes

2020-09-25 20:47 UTC, mrinehart-r7 commented on workflows/Lookup_Vuln_From_Slack/Lookup_Vuln_From_Slack.icon
> +              "expressionText": "edit-me\\s+{{argument:/.*/}}",
```suggestion
              "expressionText": "lookup-vuln\\s+{{argument:/.*/}}",
```

2020-09-25 20:47 UTC, mrinehart-r7 commented on workflows/Lookup_Vuln_From_Slack/Lookup_Vuln_From_Slack.icon
> +                  "value": "edit-me\\s+"
```suggestion
                  "value": "lookup-vuln\\s+"
```

2020-09-25 21:03 UTC, merged