New Workflow: Manage Vulnerability Exceptions with Connect
rapid7/insightconnect-workflows pull request #339
Opened 2020-09-23 22:00 UTC by sengleson-r7

New workflow for the Discover tab, automatically approve exceptions for low-risk low-scope vulns. Tested under various conditions -- multiple exception scopes, various risk thresholds -- with success, more testing welcome.

<img width="1341" alt="artifact" src="https://user-images.githubusercontent.com/34718704/94074055-5ffff180-fdad-11ea-8847-46bf3e1873a8.png">

<img width="1311" alt="job" src="https://user-images.githubusercontent.com/34718704/94074065-62fae200-fdad-11ea-912d-99352a508ce9.png">
<img width="502" alt="vm" src="https://user-images.githubusercontent.com/34718704/94074069-64c4a580-fdad-11ea-8ea3-2cfb2429afc6.png">
<img width="383" alt="workflow" src="https://user-images.githubusercontent.com/34718704/94074071-655d3c00-fdad-11ea-8b97-79101c231308.png">
<img width="995" alt="sengleson_—_-zsh_—_141×49_and_Comparing_master___discover-exception-management_·_rapid7_insightconnect-workflows" src="https://user-images.githubusercontent.com/34718704/94074089-727a2b00-fdad-11ea-8944-a5f1ad82788f.png">

2020-09-28 16:47 UTC, lmilby-r7 requested changes

2020-09-28 16:47 UTC, lmilby-r7 commented on workflows/Manage_Vulnerability_Exceptions_With_InsightConnect/help.md
> +
Are we missing references supplied in the setup?

2020-09-28 17:03 UTC, sengleson-r7 commented on workflows/Manage_Vulnerability_Exceptions_With_InsightConnect/help.md
> +
Nope! This workflow just uses VM & Connect, we don't typically include references for R7 products, just third party products

2020-09-28 17:38 UTC, lmilby-r7 approved these changes

2020-09-30 23:19 UTC, jschipp-r7 approved these changes

2020-09-30 23:24 UTC, merged