Discover asset details scan
rapid7/insightconnect-workflows pull request #340
Opened 2020-09-23 23:13 UTC by sengleson-r7

New workflow for VM Discover Experience. Workflow gets asset details from InsightVM and includes an easy option to enable a scan asset step. Would really appreciate a detailed review of the setup instructions on this one <3

<img width="1326" alt="artifact" src="https://user-images.githubusercontent.com/34718704/94083251-9f334000-fdb7-11ea-9f43-f84522a31f57.png">
<img width="1343" alt="job" src="https://user-images.githubusercontent.com/34718704/94083258-a2c6c700-fdb7-11ea-9f6e-1a2e95cc8c1f.png">
<img width="1406" alt="test" src="https://user-images.githubusercontent.com/34718704/94083260-a4908a80-fdb7-11ea-83d1-ef447f1f40c0.png">
<img width="163" alt="workflow" src="https://user-images.githubusercontent.com/34718704/94083263-a78b7b00-fdb7-11ea-9703-2bc97a05cbf9.png">
<img width="997" alt="sengleson_—_-zsh_—_141×49_and_Comparing_master___discover-asset-details-scan_·_rapid7_insightconnect-workflows" src="https://user-images.githubusercontent.com/34718704/94083318-afe3b600-fdb7-11ea-9c70-07f6d1daa320.png">

2020-09-28 16:50 UTC, lmilby-r7 requested changes

2020-09-28 16:50 UTC, lmilby-r7 commented on workflows/Get_InsightVM_Asset_Details_And_Scan_Asset_From_InsightConnect/help.md
> +
Looks like we are missing references from the setup and description here.

2020-09-28 17:39 UTC, lmilby-r7 approved these changes

2020-09-30 23:26 UTC, jschipp-r7 commented on workflows/Get_InsightVM_Asset_Details_And_Scan_Asset_From_InsightConnect/workflow.spec.yaml
> +description: "Fetch host details and scan target asset with a simple InsightConnect API request."
```suggestion
description: "Fetch host details and scan target asset on-demand using the workflow Run."
```

2020-10-01 19:28 UTC, jschipp-r7 requested changes
@sengleson-r7 Can we update this title too?

2020-10-05 15:06 UTC, jschipp-r7 requested changes
@sengleson-r7

2020-10-05 15:06 UTC, jschipp-r7 commented on workflows/Get_InsightVM_Asset_Details_And_Scan_Asset_From_InsightConnect/help.md
> +## Readme
This section will break the Extension Library rendering because it reads the whole `## Setup` section which is just a few sentences in this PR.. Also, do we need to make this a new heading? It will be the only workflow that uses it. Better to keep it under Setup or put under Usage.

2020-10-06 13:49 UTC, sengleson-r7 commented on workflows/Get_InsightVM_Asset_Details_And_Scan_Asset_From_InsightConnect/help.md
> +## Readme
Gotchya! I removed the readme header so this is part of the ## Setup section

2020-10-06 20:22 UTC, jschipp-r7 requested changes

2020-10-06 20:22 UTC, jschipp-r7 commented on workflows/Get_InsightVM_Asset_Details_And_Scan_Asset_From_InsightConnect/workflow.spec.yaml
> +title: "Get InsightVM Asset Details and Scan Asset from InsightConnect"
We should do a similar change to what we had in the other workflow:

e.g.
        - "name": "Manage Vulnerability Exceptions with InsightConnect",
        + "name": "Automate Vulnerability Exception Management in InsightVM",

2020-10-06 20:22 UTC, jschipp-r7 commented on workflows/Get_InsightVM_Asset_Details_And_Scan_Asset_From_InsightConnect/workflow.spec.yaml
> +name: Get_InsightVM_Asset_Details_And_Scan_Asset_From_InsightConnect
Need to update `name` and directory name to match convention in the workflow repo
```suggestion
name: Get_InsightVM_Asset_Details_and_Scan_Asset_from_InsightConnect
```

2020-10-20 01:56 UTC, sengleson-r7 commented on workflows/Get_InsightVM_Asset_Details_And_Scan_Asset_From_InsightConnect/workflow.spec.yaml
> +title: "Get InsightVM Asset Details and Scan Asset from InsightConnect"
Changed to "Get Asset Details and Scan Asset with InsightVM".

2020-10-20 12:28 UTC, jschipp-r7 commented on workflows/Get_InsightVM_Asset_Details_And_Scan_Asset_From_InsightConnect/help.md
> +
```suggestion
```

2020-10-20 12:30 UTC, jschipp-r7 submitted a review, later dismissed
- Directory must be updated to match `name` in spec, as well as any other references
- Missing references in the References section in help.md

2020-10-20 14:32 UTC, sengleson-r7 commented
>     * Missing references in the References section in help.md

What do we typically reference when a workflow only includes Rapid7 products?

2020-10-20 14:52 UTC, jschipp-r7 commented
> > ```
> > * Missing references in the References section in help.md
> > ```
> 
> What do we typically reference when a workflow only includes Rapid7 products?

Links to Rapid7 product documentation that may help

2020-10-20 21:12 UTC, zyoutz-r7 approved these changes

2020-10-20 21:45 UTC, tschmidtke-r7 approved these changes

2020-10-20 22:12 UTC, merged