SOAR_2919 Update Plugin Versions
rapid7/insightconnect-workflows pull request #341
Opened 2020-09-24 18:18 UTC by ekim-r7

## Description
- Bump Fortinet Fortigate, HTML, and Microsoft Teams plugins

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 31.514ms
```

2020-09-24 18:21 UTC, jmcadams-r7 requested changes
Need to bump the version in the yaml and help.md files.

2020-09-24 18:32 UTC, jmcadams-r7 submitted a review, later dismissed

2020-09-24 19:08 UTC, ncramer-r7 requested changes
Might want to update a bunch of the Teams steps so that you don't have to manually change the _change_me_ fields for each step. Keep the first teams action with the _change_me_ fields, but reference that step instead of manually putting _change me_ for the subsequent actions

2020-09-24 20:53 UTC, mrinehart-r7 commented
> Might want to update a bunch of the Teams steps so that you don't have to manually change the _change_me_ fields for each step. Keep the first teams action with the _change_me_ fields, but reference that step instead of manually putting _change me_ for the subsequent actions

👍 for this, that's a good idea

2020-09-25 16:10 UTC, jmcadams-r7 approved these changes

2020-09-25 16:20 UTC, ncramer-r7 approved these changes

2020-09-25 16:44 UTC, mrinehart-r7 approved these changes

2020-09-25 16:44 UTC, merged