Block Host with Cisco ASA from Microsoft Teams
rapid7/insightconnect-workflows pull request #353
Opened 2020-10-16 18:42 UTC by r7-kszczepanskagorna

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment
```
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 87.062ms
```
icon-validate

```
### Screenshots

#### Workflow Builder

![workflow1](https://user-images.githubusercontent.com/65252060/96296401-86512f80-0fef-11eb-8a0c-9e9c81e1f49c.png)

![workflow2](https://user-images.githubusercontent.com/65252060/96296414-88b38980-0fef-11eb-823f-cd542e0bc81d.png)

![workflow3](https://user-images.githubusercontent.com/65252060/96296423-8a7d4d00-0fef-11eb-86d6-5886fb3413cc.png)

#### Job

![teams1](https://user-images.githubusercontent.com/65252060/96296434-8f420100-0fef-11eb-9631-65f3cdc4b20b.png)
![teams2](https://user-images.githubusercontent.com/65252060/96296440-92d58800-0fef-11eb-823b-242e01e3932b.png)

![teams3](https://user-images.githubusercontent.com/65252060/96296447-949f4b80-0fef-11eb-913a-4d41b8264af3.png)

#### Artifact

![artifact1](https://user-images.githubusercontent.com/65252060/96296460-9832d280-0fef-11eb-8def-c73444e59f89.png)

![artifact2](https://user-images.githubusercontent.com/65252060/96296466-99fc9600-0fef-11eb-8854-9bc61b8a3549.png)

```

2020-10-19 13:54 UTC, jmcadams-r7 approved these changes

2020-10-19 15:22 UTC, jschipp-r7 requested changes
Capitalization isn't consistent in step names - there's a quite a few.

e.g. `IP address unblocked` should be `IP Address Unblocked`
        `Unblock IP addresses` should be `Unblock IP Addresses`

2020-10-19 15:22 UTC, jschipp-r7 commented on workflows/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams/help.md
> +This workflow blocks or unblocks a IPv4 and IPv6 addresses with Cisco ASA via Microsoft Teams command and reports information back to Microsoft Teams.
```suggestion
This workflow blocks or unblocks IPv4 and IPv6 addresses with Cisco ASA via Microsoft Teams command and reports information back to Microsoft Teams.
```

2020-10-19 15:22 UTC, jschipp-r7 commented on workflows/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams/help.md
> +
THere's an extra newline here

2020-10-19 15:22 UTC, jschipp-r7 commented on workflows/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams/help.md
> +
THere's an extra newline here

2020-10-19 15:22 UTC, jschipp-r7 commented on workflows/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams/help.md
> +_There is no troubleshooting information at this time_
```suggestion
The REST API server must be installed and enabled on the Cisco ASA device this plugin connects to. Cisco provides online documentation for this available [here](https://www.cisco.com/c/en/us/td/docs/security/asa/api/qsg-asa-api.html). In addition, the user account must have the necessary permissions for the intended actions:

* Actions that retrieve or check data require Cisco privilege level 5 or greater
* Actions that change or modify data require Cisco privilege level 15
```

2020-10-19 15:22 UTC, jschipp-r7 commented on workflows/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams/workflow.spec.yaml
> +description: This workflow blocks or unblocks a IPv4 and IPv6 addresses with Cisco ASA via Microsoft Teams
```suggestion
description: This workflow blocks or unblocks IPv4 and IPv6 addresses with Cisco ASA via Microsoft Teams
```

2020-10-19 15:22 UTC, jschipp-r7 commented on workflows/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams.icon
> +                "message": "⚠️ Cisco ASA support only IPv4 and IPv6 addresses. Check address input and try again. ⚠️",
```suggestion
                "message": "⚠️ Cisco ASA only suppors IPv4 and IPv6 addresses. Check the address input and try again. ⚠️",
```

2020-10-19 17:46 UTC, jschipp-r7 commented
Let's remove the API screenshots too.

2020-10-19 18:12 UTC, mrinehart-r7 requested changes

2020-10-19 18:12 UTC, mrinehart-r7 commented on workflows/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams.icon
> +        "description": "This workflow blocks or unblocks an IPv4 or IPv6 addresses with Cisco ASA via Microsoft Teams command and reports information back to Microsoft Teams .",
```suggestion
        "description": "This workflow blocks or unblocks an IPv4 or IPv6 addresses with Cisco ASA via Microsoft Teams command and reports information back to Microsoft Teams.",
```

2020-10-20 19:42 UTC, jschipp-r7 commented on workflows/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams/help.md
> +
```suggestion
```

2020-10-20 19:44 UTC, jschipp-r7 commented on workflows/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams.icon
> +                "group": "InsightConnect_Block_List"
```suggestion
                "group": "change_me"
```

2020-10-20 19:44 UTC, jschipp-r7 commented on workflows/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams.icon
> +                "group": "InsightConnect_Block_List"
```suggestion
                "group": "change_me"
```

2020-10-20 19:47 UTC, jschipp-r7 commented on workflows/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams.icon
> +                "group": "InsightConnect_Block_List"
```suggestion
                "group": "change_me"
```

2020-10-20 21:03 UTC, jschipp-r7 requested changes
@r7-kszczepanskagorna can you make the following changes from the Slack PR here
https://github.com/rapid7/insightconnect-workflows/pull/355

2020-10-22 17:14 UTC, mrinehart-r7 requested changes

2020-10-22 17:14 UTC, mrinehart-r7 commented on workflows/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams.icon
> +        "description": "This workflow blocks or unblocks an IPv4 or IPv6 addresses with Cisco ASA via Microsoft Teams command and reports information back to Microsoft Teams.",
```suggestion
        "description": "This workflow blocks or unblocks IPv4 or IPv6 addresses with Cisco ASA via Microsoft Teams command and reports information back to Microsoft Teams.",
```

2020-10-22 17:18 UTC, mrinehart-r7 requested changes

2020-10-22 17:18 UTC, mrinehart-r7 commented on workflows/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams/help.md
> +The workflow works by adding and removing address objects from an existing network group tied to a Deny firewall policy in your Cisco ASA Firewall.
```suggestion

The workflow works by adding and removing address objects from an existing network group tied to a Deny firewall policy in your Cisco ASA Firewall.
```

2020-10-22 17:18 UTC, mrinehart-r7 commented on workflows/Block_Host_with_Cisco_ASA_Firewall_from_Microsoft_Teams/help.md
> +When an address is added to the group, it's blocked; when an address is removed from a group, it's unblocked. These are best practices for automating the blocking of hosts.
```suggestion

When an address is added to the group, it's blocked; when an address is removed from a group, it's unblocked. These are best practices for automating the blocking of hosts.
```

2020-10-22 17:20 UTC, mrinehart-r7 approved these changes

2020-10-28 21:01 UTC, merged