Blacklist Indicators with Crowdstrike Falcon from Slack
rapid7/insightconnect-workflows pull request #354
Opened 2020-10-20 18:45 UTC by r7-kszczepanskagorna

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

* icon-validate
```
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 90.655ms

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

![workflow1](https://user-images.githubusercontent.com/65252060/96630188-f2e06d00-1314-11eb-8ba7-bc98ee5e44fb.png)

![workflow2](https://user-images.githubusercontent.com/65252060/96630201-f5db5d80-1314-11eb-9599-8c81e1557bdd.png)

#### Job

![slack1](https://user-images.githubusercontent.com/65252060/96630217-f8d64e00-1314-11eb-847f-252ed02417fa.png)
![slack2](https://user-images.githubusercontent.com/65252060/96630230-fd026b80-1314-11eb-8004-d7c05b88a556.png)

![slack3](https://user-images.githubusercontent.com/65252060/96630236-fecc2f00-1314-11eb-897b-8a5abd2d943b.png)

#### Artifact

![artifact1](https://user-images.githubusercontent.com/65252060/96630262-07246a00-1315-11eb-866b-d0470942a200.png)
![artifact2](https://user-images.githubusercontent.com/65252060/96630268-08559700-1315-11eb-8bd7-cb927b68c666.png)
![artifact3](https://user-images.githubusercontent.com/65252060/96630271-0986c400-1315-11eb-8198-cc4f2a9d2284.png)
![artifact4](https://user-images.githubusercontent.com/65252060/96630272-0a1f5a80-1315-11eb-90b2-7187bbb1f9d4.png)
![artifact5](https://user-images.githubusercontent.com/65252060/96630273-0ab7f100-1315-11eb-893b-5325425ff902.png)

```

2020-10-22 16:22 UTC, jmcadams-r7 submitted a review, later dismissed

2020-10-22 16:49 UTC, mhofert-r7 submitted a review, later dismissed

2020-10-26 17:55 UTC, mrinehart-r7 requested changes

2020-10-26 17:55 UTC, mrinehart-r7 commented on workflows/Blacklist_Indicators_with_CrowdStrike_Falcon_from_Slack/help.md
> +Use the simplicity of a chat command in Slack to block an indicator such as IPv6, IPv4, MD5 hash, SHA256 and domain in your Crowdstrike Falcon.
```suggestion
Use the simplicity of a chat command in Slack to block an indicator such as IPv4 and IPv6 address, MD5 and SHA256 hashes, and domains in CrowdStrike Falcon.
```

2020-10-26 17:55 UTC, mrinehart-r7 commented on workflows/Blacklist_Indicators_with_CrowdStrike_Falcon_from_Slack/help.md
> +* [Crowdstrike](https://www.crowdstrike.com/)
```suggestion
* [CrowdStrike](https://www.crowdstrike.com/)
```

2020-10-26 17:55 UTC, mrinehart-r7 commented on workflows/Blacklist_Indicators_with_CrowdStrike_Falcon_from_Slack/help.md
> +* [Crowdstrike Falcon API](https://falcon.crowdstrike.com/support/documentation)
```suggestion
* [CrowdStrike Falcon API](https://falcon.crowdstrike.com/support/documentation)
```

2020-10-26 17:58 UTC, mrinehart-r7 approved these changes

2020-10-26 17:58 UTC, merged