Carbon Black EDR - New Workflow - Quarantine Endpoint with Slack and Microsoft Teams
rapid7/insightconnect-workflows pull request #357
Opened 2020-10-21 20:23 UTC by dmandyna-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment
#### Icon-Validate

<details>

```
[*] Validating workflow at ./Quarantine_Endpoint_with_Carbon_Black_EDR_from_Slack/

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 55.972ms
```

<summary>
icon-validate ./Quarantine_Endpoint_with_Carbon_Black_EDR_from_Slack/
</summary>
</details>

<details>

```
[*] Validating workflow at ./Quarantine_Endpoint_with_Carbon_Black_EDR_from_Microsoft_Teams/

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 46.955ms
```

<summary>
icon-validate ./Quarantine_Endpoint_with_Carbon_Black_EDR_from_Microsoft_Teams/
</summary>
</details>

### Screenshots

#### Workflow Builder

##### Slack

<img width="371" alt="workflow" src="https://user-images.githubusercontent.com/66844174/96778330-71a3db80-13e3-11eb-9154-f923bc1f0b1a.png">

##### Teams

![workflow](https://user-images.githubusercontent.com/66844174/96778337-78325300-13e3-11eb-8447-9e923fce1de2.png)

#### Job

##### Slack

![job](https://user-images.githubusercontent.com/66844174/96778360-81bbbb00-13e3-11eb-9a33-6ab44b5ebb23.png)

##### Teams

![job](https://user-images.githubusercontent.com/66844174/96778368-854f4200-13e3-11eb-945e-74f9d9c8fd3b.png)

#### Artifact

##### Slack

<img width="1488" alt="artifact1" src="https://user-images.githubusercontent.com/66844174/96778399-8da77d00-13e3-11eb-893d-107ec3fd47c4.png">

<img width="1484" alt="artifact2" src="https://user-images.githubusercontent.com/66844174/96778404-90a26d80-13e3-11eb-9210-f09d8a8494fa.png">

##### Teams

![artifact1](https://user-images.githubusercontent.com/66844174/96778412-9435f480-13e3-11eb-94b8-c2ade01ff2f6.png)

![artifact2](https://user-images.githubusercontent.com/66844174/96778416-94ce8b00-13e3-11eb-971a-caa8dca5f076.png)

2020-10-22 16:29 UTC, jmcadams-r7 requested changes
Need to remove offending screenshots. They're of the job details page. I think they need to be of the artifacts (or just remove them)

https://github.com/rapid7/insightconnect-workflows/blob/d1e5142cbb732b919baee29a259442620a7f9bf4/workflows/Quarantine_Endpoint_with_Carbon_Black_EDR_from_Microsoft_Teams/screenshots/job.png
That screenshot is wrong I think. It should be removed. (I don't know how to comment on a whole file in github). (edited) 




Joey McAdams  2 minutes ago
Same with this one.
https://github.com/rapid7/insightconnect-workflows/blob/d1e5142cbb732b919baee29a259442620a7f9bf4/workflows/Quarantine_Endpoint_with_Carbon_Black_EDR_from_Slack/screenshots/job.png (edited)

2020-10-22 17:37 UTC, mrinehart-r7 requested changes

2020-10-22 17:37 UTC, mrinehart-r7 commented on workflows/Quarantine_Endpoint_with_Carbon_Black_EDR_from_Slack/help.md
> +Find the host name on the list and check the Status column for the quarantine status.
```suggestion
Find the hostname on the list and check the Status column for the quarantine status. 
```

2020-10-22 17:37 UTC, mrinehart-r7 commented on workflows/Quarantine_Endpoint_with_Carbon_Black_EDR_from_Slack/Quarantine_Endpoint_with_Carbon_Black_EDR_from_Slack.icon
> +                "message": ":exclamation: The input could not be correctly parsed. :exclamation:\n\nThis workflow will quarantine or unquarantine an endpoint using Carbon Black EDR. To use this workf
```suggestion
                "message": ":exclamation: The input could not be correctly parsed. :exclamation:\n\nThis workflow will quarantine or unquarantine an endpoint using Carbon Black EDR. To use this workflow provide a `quarantine-endpoint` or `unquarantine-endpoint` command in Slack along with a host to perform the action on by its hostname.\n\nFor example:\n\n* `@Rapid7 InsightConnect quarantine-endpoint USER-DESKTOP`\n* `@Rapid7 InsightConnect unquarantine-endpoint USER-DESKTOP`\n",
```

2020-10-22 17:37 UTC, mrinehart-r7 commented on workflows/Quarantine_Endpoint_with_Carbon_Black_EDR_from_Slack/Quarantine_Endpoint_with_Carbon_Black_EDR_from_Slack.icon
> +                "message": ":x: Action: `{{[de5a776f-74a5-4c62-bcd8-c988f1b522c8].[action]}}` on the host `{{[de5a776f-74a5-4c62-bcd8-c988f1b522c8].[host]}}` was unsuccessful. :x:\n\nThis could be be
```suggestion
                "message": ":x: Action: `{{[de5a776f-74a5-4c62-bcd8-c988f1b522c8].[action]}}` on the host `{{[de5a776f-74a5-4c62-bcd8-c988f1b522c8].[host]}}` was unsuccessful. :x:\n\nThis could be because the hostname is incorrect or the host doesn't exist within Carbon Black EDR.\n\nSee job logs at {{[$job].[URL]}} for more information.",
```

2020-10-22 17:37 UTC, mrinehart-r7 commented on workflows/Quarantine_Endpoint_with_Carbon_Black_EDR_from_Microsoft_Teams/Quarantine_Endpoint_with_Carbon_Black_EDR_from_Microsoft_Teams.icon
> +                "message_content": "🚨 Action: <code>{{[afd380e8-b0f5-4328-a036-8520c4b0a6ea].[message].[first_word]}}</code> on the host <code>{{[de5a776f-74a5-4c62-bcd8-c988f1b522c8].[host]}}</code>
```suggestion
                "message_content": "🚨 Action: <code>{{[afd380e8-b0f5-4328-a036-8520c4b0a6ea].[message].[first_word]}}</code> on the host <code>{{[de5a776f-74a5-4c62-bcd8-c988f1b522c8].[host]}}</code> was unsuccessful. 🚨\n<br>\nThis could be because the hostname is incorrect or the host doesn't exist within Carbon Black EDR.\n<br>\nSee <a href=\"{{[$job].[URL]}}\">job logs</a> for more information.",
```

2020-10-22 17:39 UTC, mrinehart-r7 submitted a review, later dismissed
Approved, just need to address @jmcadams-r7 comments

2020-10-22 20:13 UTC, dmandyna-r7 commented
@jmcadams-r7 Thanks for the review. I've just pushed a change removing the screenshots from screenshots folder and from the workflow.spec.yaml file.

2020-10-28 20:24 UTC, mrinehart-r7 approved these changes

2020-10-28 20:24 UTC, merged