Blacklist Hash with VMware Carbon Black EDR from Slack
rapid7/insightconnect-workflows pull request #358
Opened 2020-10-22 20:09 UTC by r7-kszczepanskagorna

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

icon-validate
```[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 68.75399999999999ms

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

![workflow](https://user-images.githubusercontent.com/65252060/96923603-d0378b00-14b1-11eb-8e56-4cd851bddced.png)

#### Job

![slack1](https://user-images.githubusercontent.com/65252060/96923618-d463a880-14b1-11eb-9579-1a6d58192cd5.png)

![slack2](https://user-images.githubusercontent.com/65252060/96923621-d62d6c00-14b1-11eb-809f-16915a6b98b2.png)

![slack3](https://user-images.githubusercontent.com/65252060/96923625-d7f72f80-14b1-11eb-86a7-31cefe2f3c76.png)

![slack4](https://user-images.githubusercontent.com/65252060/96923629-d9285c80-14b1-11eb-8233-3f40166dbe60.png)

#### Artifact

![artifact](https://user-images.githubusercontent.com/65252060/96923640-dc234d00-14b1-11eb-8d8c-ca09aad2ada8.png)

```

2020-10-22 20:28 UTC, jschipp-r7 commented on workflows/Blacklist_Hash_with_VMware_Carbon_Black_EDR_from_Slack/Blacklist_Hash_with_VMware_Carbon_Black_EDR_from_Slack.icon
> +                "content": "This workflow will blacklist MD5 hashes globally in Carbon Black EDR. To use this workflow provide a blacklist or command in Slack and a hash to perform the command on.\n\
```suggestion
                "content": "This workflow will blacklist MD5 hashes globally in Carbon Black EDR. To use this workflow provide the blacklist-hash command in Slack and an MD5 hash to perform the command on.\n\nFor example:\n\n* `@Rapid7 InsightConnect blacklist-hash 9de5069c5afe602b2ea0a04b66beb2c0`"
```

2020-10-22 20:30 UTC, jschipp-r7 requested changes
@r7-kszczepanskagorna for this workflow we shouldn't use Pattern Match because the MD5 can be extracted automatically from the Slack step and the command (i.e. blacklist-hash) is stored in the variable `first_word` of the Slack step - so that can be passed directly to Automated Decision without needing to extract it first with Pattern Match

2020-10-26 13:42 UTC, jschipp-r7 requested changes
Can a user provide one or more MD5 hashes like the other workflows? If not, let's support that

```
@Rapid7 InsightConnect blacklist-hash 9de5069c5afe602b2ea0a04b66beb2c0 d8e8fca2dc0f896fd7cb4cb0031ba249
```

2020-10-26 13:42 UTC, jschipp-r7 commented on workflows/Blacklist_Hash_with_VMware_Carbon_Black_EDR_from_Slack/Blacklist_Hash_with_VMware_Carbon_Black_EDR_from_Slack.icon
> +        "name": "Blacklist Hash VMware Carbon Black EDR from Slack",
Regression in name

```suggestion
        "name": "Blacklist Hash with VMware Carbon Black EDR from Slack",
```

2020-11-06 00:53 UTC, mrinehart-r7 requested changes

2020-11-06 00:53 UTC, mrinehart-r7 commented on workflows/Blacklist_Hash_with_VMware_Carbon_Black_EDR_from_Slack/Blacklist_Hash_with_VMware_Carbon_Black_EDR_from_Slack.icon
> +        "description": "This workflow will blacklist a MD5 hash globally in Carbon Black EDR from a Slack command.",
```suggestion
        "description": "This workflow will blacklist an MD5 hash globally in VMware Carbon Black EDR from a Slack command.",
```

2020-11-06 00:53 UTC, mrinehart-r7 commented on workflows/Blacklist_Hash_with_VMware_Carbon_Black_EDR_from_Slack/Blacklist_Hash_with_VMware_Carbon_Black_EDR_from_Slack.icon
> +                "message": "🚀 Request received! Running Carbon Black EDR workflow... 🚀",
```suggestion
                "message": "🚀 Request received! Running VMware Carbon Black EDR workflow... 🚀",
```

2020-11-06 00:53 UTC, mrinehart-r7 commented on workflows/Blacklist_Hash_with_VMware_Carbon_Black_EDR_from_Slack/Blacklist_Hash_with_VMware_Carbon_Black_EDR_from_Slack.icon
> +                "content": ":rotating_light: Hash action successfully executed for `{{[cbfdb9ff-28e2-4e9e-a643-7605ca1c279e].[$item]}}` :rotating_light:"
```suggestion
                "content": ":rotating_light: Blacklist hash action successfully executed for `{{[cbfdb9ff-28e2-4e9e-a643-7605ca1c279e].[$item]}}` :rotating_light:"
```
Just a little more clarification to the user

2020-11-06 00:53 UTC, mrinehart-r7 commented on workflows/Blacklist_Hash_with_VMware_Carbon_Black_EDR_from_Slack/Blacklist_Hash_with_VMware_Carbon_Black_EDR_from_Slack.icon
> +                "content": "Carbon Black EDR requires a MD5 hash but it was not provided. Please run this workflow again with a MD5 hash.\n\nFor example:\n\n* `@Rapid7 InsightConnect blacklist-hash 9
```suggestion
                "content": "VMware Carbon Black EDR requires an MD5 hash but one was not provided. Please run this workflow again with an MD5 hash.\n\nFor example:\n\n* `@Rapid7 InsightConnect blacklist-hash 9de5069c5afe602b2ea0a04b66beb2c0`\n"
```

2020-11-06 00:53 UTC, mrinehart-r7 commented on workflows/Blacklist_Hash_with_VMware_Carbon_Black_EDR_from_Slack/help.md
> +This workflow blacklists a MD5 hashes globally with VMware Carbon Black EDR via Slack command and reports information back to Slack.
```suggestion
This workflow blacklists MD5 hashes globally with VMware Carbon Black EDR via Slack command and reports information back to Slack.
```

2020-11-06 19:23 UTC, mrinehart-r7 approved these changes

2020-11-06 19:23 UTC, merged