New Workflow - VM Events Trigger - High Risk Vuln Notification in Slack
rapid7/insightconnect-workflows pull request #368
Opened 2020-11-16 22:55 UTC by sengleson-r7

New workflow using the InsightVM Events trigger!

<img width="475" alt="workflow1" src="https://user-images.githubusercontent.com/34718704/99317888-9b51f600-281b-11eb-9891-5b53fc311a52.png">

<img width="499" alt="workflow2" src="https://user-images.githubusercontent.com/34718704/99317883-99883280-281b-11eb-889d-2e9c2b7130d2.png">

<img width="750" alt="slack_output" src="https://user-images.githubusercontent.com/34718704/99317901-a0af4080-281b-11eb-9f08-00e8a5932c89.png">

<img width="956" alt="job" src="https://user-images.githubusercontent.com/34718704/99317903-a1e06d80-281b-11eb-8b0c-4cdaa80511c6.png">

<img width="1382" alt="test" src="https://user-images.githubusercontent.com/34718704/99317894-9d1bb980-281b-11eb-9ca9-08ead72bd233.png">

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Tested in Integrations Alliance environment successfully

2020-11-17 12:59 UTC, cmchugh-r7 commented on workflows/Alert_on_New_High_Risk_Vulnerability_in_InsightVM_with_Slack/Alert_on_New_High_Risk_Vulnerability_in_InsightVM_with_Slack.icon
> +    "triggers": [
Please re-export and push this after prod release is out this morning, it has a fix for exporting the vm triggers. This icon file is missing an identifier :(

2020-11-17 13:00 UTC, cmchugh-r7 commented on workflows/Alert_on_New_High_Risk_Vulnerability_in_InsightVM_with_Slack/help.md
> +_There is no troubleshooting information at this time_
Should this include a note about lag in the trigger?

2020-11-17 13:02 UTC, cmchugh-r7 commented on workflows/Alert_on_New_High_Risk_Vulnerability_in_InsightVM_with_Slack/help.md
> +After configuring the Slack channel setting, activate the workflow. Any newly discovered vulnerability will generate a webhook event, which will trigger your workflow, which will look up the vulnerab
Is it worth including a note about how to modify the CVSS score in case users want something other than 7?

2020-11-17 13:03 UTC, cmchugh-r7 requested changes
a few small suggestions! only significant bit of feedback is that a new icon file needs to be exported+pushed after prod fix goes out today.

2020-11-17 13:44 UTC, cmchugh-r7 commented
Fix just got released so you should be good to export this again!

2020-11-17 23:08 UTC, sengleson-r7 commented on workflows/Alert_on_New_High_Risk_Vulnerability_in_InsightVM_with_Slack/help.md
> +After configuring the Slack channel setting, activate the workflow. Any newly discovered vulnerability will generate a webhook event, which will trigger your workflow, which will look up the vulnerab
yes! great call

2020-11-17 23:21 UTC, sengleson-r7 commented on workflows/Alert_on_New_High_Risk_Vulnerability_in_InsightVM_with_Slack/help.md
> +_There is no troubleshooting information at this time_
yes, good call

2020-11-18 12:42 UTC, cmchugh-r7 approved these changes

2020-11-18 14:01 UTC, lmilby-r7 approved these changes

2020-11-18 16:06 UTC, merged