Alert on Presence of Zero Logon Vulnerability - Slack
rapid7/insightconnect-workflows pull request #374
Opened 2020-11-23 04:27 UTC by tharward-r7

TODO:

- [ ] Test with actual VM trigger
- [ ] Successful Job screenshot

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [x] Workflow verified as working in a test
- [x] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [x] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [x] Workflow includes a detailed Description
- [x] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [x] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details (Slack Step?)
- [x] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [x] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [x] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

### Screenshots

<img width="1680" alt="test" src="https://user-images.githubusercontent.com/57955862/99929174-35cda000-2d1a-11eb-8cb5-3cbedf384d49.png">

<img width="669" alt="slack_output" src="https://user-images.githubusercontent.com/57955862/99929177-382ffa00-2d1a-11eb-8f80-7341403f4ecb.png">

<img width="444" alt="workflow2" src="https://user-images.githubusercontent.com/57955862/99929178-38c89080-2d1a-11eb-9f76-c7f2fb6eab28.png">

<img width="505" alt="workflow1" src="https://user-images.githubusercontent.com/57955862/99929179-38c89080-2d1a-11eb-9751-478083f42330.png">

2020-12-02 15:53 UTC, cmchugh-r7 commented on workflows/Alert_on_Presence_of_Zero_Logon_Vulnerability_with_Slack/workflow.spec.yaml
> +#    - name: job.png
should this be revised to reference the test.png, or will you be updating with a job png?

2020-12-02 15:55 UTC, cmchugh-r7 commented
looks good aside from needing the real job!

2020-12-02 16:32 UTC, sengleson-r7 requested changes

2020-12-02 16:32 UTC, sengleson-r7 commented on workflows/Alert_on_Presence_of_Zero_Logon_Vulnerability_with_Slack/help.md
> +|Rapid7 InsightVM|4.7.0|1|
```suggestion
```

2020-12-02 16:32 UTC, sengleson-r7 commented on workflows/Alert_on_Presence_of_Zero_Logon_Vulnerability_with_Slack/help.md
> +* [Slack](https://slack.com)
```suggestion
* [Slack](https://slack.com)
* [InsightVM Events Trigger](https://docs.rapid7.com/insightconnect/set-up-an-insightvm-events-trigger)
```

2020-12-02 16:32 UTC, sengleson-r7 commented on workflows/Alert_on_Presence_of_Zero_Logon_Vulnerability_with_Slack/help.md
> +After subscribing to the vulnerabilities found webhook event, return to the workflow editor and click the "Loop Over found Vulnerabilities" loop. Within the loop, click on the "Post to Slack" ChatOps
```suggestion
After subscribing to the vulnerabilities found webhook event, return to the workflow editor and click the "Loop over Found Vulnerabilities" loop. Within the loop, click on the "Post to Slack" ChatOps step, and change the field "Enter #channel or @username" from `change_me` to a channel name in your Slack environment where you would like vulnerability notifications delivered. We recommend a private channel with representatives from security and remediation teams for the best visibility.
```

2020-12-02 16:32 UTC, sengleson-r7 commented on workflows/Alert_on_Presence_of_Zero_Logon_Vulnerability_with_Slack/workflow.spec.yaml
> +  keywords: [chat, slack]
```suggestion
  keywords: [chat, slack, cloud_enabled]
```

2020-12-02 23:39 UTC, sengleson-r7 submitted a review, later dismissed

2020-12-04 02:03 UTC, jschipp-r7 commented on workflows/Alert_on_Presence_of_Zero_Logon_Vulnerability_with_Slack/help.md
> +This workflow listens for InsightVM Webhook Events for newly discovered vulnerabilities, checks if a Zero Logon (CVE-2020-1472 or derivitave) vulnerability is present, and if found, posts a notificat
```suggestion
This workflow listens for InsightVM Webhook Events for newly discovered vulnerabilities, checks if a Zero Logon (CVE-2020-1472 or derivative) vulnerability is present, and if found, posts a notification to a Slack channel.
```

2020-12-04 02:06 UTC, jschipp-r7 commented on workflows/Alert_on_Presence_of_Zero_Logon_Vulnerability_with_Slack/Alert_on_Presence_of_Zero_Logon_Vulnerability_with_Slack.icon
> +                "recipient": "#change_me",
```suggestion
                "recipient": "change_me",
```

2020-12-04 02:07 UTC, jschipp-r7 approved these changes

2020-12-04 02:07 UTC, jschipp-r7 commented
@tharward-r7 Can merge once retested

2020-12-08 20:33 UTC, sengleson-r7 approved these changes

2020-12-08 20:34 UTC, merged