Alert on Zero Logon detection - Teams
rapid7/insightconnect-workflows pull request #375
Opened 2020-11-23 04:38 UTC by tharward-r7

TODO:

- [ ] Test with a real Teams environment
- [ ] test.png
- [ ] Test with VM alert and produce successful job
- [ ] job.png

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [x] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [x] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [x] Workflow includes a detailed Description
- [x] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [x] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [x] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [x] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [x] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Screenshots

<img width="740" alt="workflow1" src="https://user-images.githubusercontent.com/57955862/99929572-b0e38600-2d1b-11eb-9963-9ee339606d93.png">

<img width="796" alt="workflow2" src="https://user-images.githubusercontent.com/57955862/99929571-b04aef80-2d1b-11eb-9de7-95543b92cd84.png">

2020-11-23 17:59 UTC, sengleson-r7 requested changes

2020-11-23 17:59 UTC, sengleson-r7 commented on workflows/Alert_on_Presence_of_Zero_Logon_Vulnerability_with_Microsoft_Teams/help.md
> +**In order to use this workflow, you will need to subscribe to the InsightVM Vulnerabilities Found webhook event. You will also need to adjust the Teams team and channel names to match your environme
```suggestion
**In order to use this workflow, you will need to subscribe to the InsightVM Vulnerabilities Found webhook event. You will also need to adjust the Microsoft Teams team and channel names to match your environment.**
```

2020-11-23 17:59 UTC, sengleson-r7 commented on workflows/Alert_on_Presence_of_Zero_Logon_Vulnerability_with_Microsoft_Teams/help.md
> +
```suggestion
|Microsoft Teams|2.2.1|1|
```

2020-11-23 17:59 UTC, sengleson-r7 commented on workflows/Alert_on_Presence_of_Zero_Logon_Vulnerability_with_Microsoft_Teams/workflow.spec.yaml
> +  keywords: [chat, slack]
```suggestion
  keywords: [chat, microsoft_teams]
```

2020-12-02 15:56 UTC, cmchugh-r7 commented on workflows/Alert_on_Presence_of_Zero_Logon_Vulnerability_with_Microsoft_Teams/workflow.spec.yaml
> +#    - name: slack_output.png
should this be updated to reference the teams screenshot?

2020-12-02 16:08 UTC, sengleson-r7 submitted a review, later dismissed

2020-12-02 16:19 UTC, sengleson-r7 requested changes

2020-12-02 16:19 UTC, sengleson-r7 commented on workflows/Alert_on_Presence_of_Zero_Logon_Vulnerability_with_Microsoft_Teams/help.md
> +After subscribing to the vulnerabilities found webhook event, return to the workflow editor and click the "Loop Over found Vulnerabilities" loop. Within the loop, click on the "Post to Microsoft Team
```suggestion
After subscribing to the vulnerabilities found webhook event, return to the workflow editor and click the "Loop over Found Vulnerabilities" loop. Within the loop, click on the "Post Message to Teams" step, and change the Team and Channel fields from `change_me` to the desired team and channel for the Teams environment where you would like vulnerability notifications delivered. We recommend a private channel with representatives from security and remediation teams for the best visibility.
```

2020-12-02 16:19 UTC, sengleson-r7 commented on workflows/Alert_on_Presence_of_Zero_Logon_Vulnerability_with_Microsoft_Teams/help.md
> +* [Microsoft Teams](https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/group-chat-software)
```suggestion
* [Microsoft Teams](https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/group-chat-software)
* [InsightVM Events Trigger](https://docs.rapid7.com/insightconnect/set-up-an-insightvm-events-trigger)
```

2020-12-02 20:11 UTC, tharward-r7 commented on workflows/Alert_on_Presence_of_Zero_Logon_Vulnerability_with_Microsoft_Teams/workflow.spec.yaml
> +#    - name: slack_output.png
Done! Thanks!

2020-12-02 21:51 UTC, sengleson-r7 submitted a review, later dismissed

2020-12-04 02:08 UTC, jschipp-r7 commented on workflows/Alert_on_Presence_of_Zero_Logon_Vulnerability_with_Microsoft_Teams/help.md
> +This workflow listens for InsightVM Webhook Events for newly discovered vulnerabilities, checks if a Zero Logon (CVE-2020-1472 or derivitave) vulnerability is present, and if found, posts a notificat
```suggestion
This workflow listens for InsightVM Webhook Events for newly discovered vulnerabilities, checks if a Zero Logon (CVE-2020-1472 or derivative) vulnerability is present, and if found, posts a notification to a Microsoft Teams channel.
```

2020-12-04 02:09 UTC, jschipp-r7 approved these changes
@tharward-r7 can merge after retesting

2020-12-08 20:35 UTC, sengleson-r7 approved these changes

2020-12-08 20:35 UTC, merged