Add new workflow Find_InsightConnect_Resources_from_Slack
rapid7/insightconnect-workflows pull request #379
Opened 2020-11-24 17:40 UTC by nhurd-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [yes] Workflow verified as working in a test
- [yes] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [yes] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [yes] Workflow includes a detailed Description
- [yes] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [yes] Triggers, Decisions, and other workflow steps include descriptions where needed
- [no; not necessary for this use case] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [yes] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [yes] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [yes] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

<img width="556" alt="Workflow" src="https://user-images.githubusercontent.com/74786214/100131336-e68a8b00-2e51-11eb-9d96-36f39d3dcebf.png">
<img width="799" alt="Slack_loop" src="https://user-images.githubusercontent.com/74786214/100131348-eb4f3f00-2e51-11eb-974b-3db57cf18886.png">
<img width="536" alt="icon-start" src="https://user-images.githubusercontent.com/74786214/100131365-ef7b5c80-2e51-11eb-92f8-5fc96f307a76.png">
<img width="520" alt="icon-help" src="https://user-images.githubusercontent.com/74786214/100131375-f30ee380-2e51-11eb-8721-f4e59e69f4d4.png">
<img width="536" alt="Getting_started_response" src="https://user-images.githubusercontent.com/74786214/100131385-f609d400-2e51-11eb-9108-db797f9bc62f.png">

#### Workflow Builder

<img width="556" alt="Workflow" src="https://user-images.githubusercontent.com/74786214/100131410-00c46900-2e52-11eb-95ec-9bcbef463a70.png">

#### Job

- No Job screenshot because this Workflow only leverages the Slack app, so I did not feel that the Job would provide any helpful information

#### Artifact

- Similar to the above thought process, this Workflow does not include an Artifact step because it only leverages the Slack app, and was designed to provide the user a simplified 'you don't have to leave Slack' experience. I did include screenshots of the Slack interactions above, which I believe are more helpful in this case.
```

2020-11-30 19:02 UTC, ncramer-r7 commented on workflows/Find_InsightConnect_Resources_from_Slack/workflow.spec.yaml
> +  keywords: [Chat, Slack]
```suggestion
  keywords: [chat, slack]
```

2020-11-30 19:06 UTC, ncramer-r7 commented on workflows/Find_InsightConnect_Resources_from_Slack/workflow.spec.yaml
> +  use_cases: [Chat, Slack]
```suggestion
  use_cases: []
```
We typically only use a set of use cases found [here](https://docs.google.com/document/d/1Z2wV5Z96jtxdz-LVsLzdl3S1aFo9RhVPODmylyJmay0) under the Workflow Tags --> Use Cases section, but I would say this workflow doesn't fit into any of those buckets

2020-11-30 19:08 UTC, ncramer-r7 commented on workflows/Find_InsightConnect_Resources_from_Slack/help.md
> +
```suggestion
_This workflow will trigger in any direct messages to the InsightConnect app, or any message in a channel directed @ the InsightConnect app. The app must first be invited to the channel in order to trigger the workflow this way._

To run the workflow, send a direct message to your InsightConnect Slack app or @ the app in a channel starting with the command `icon-start`.

For example, in a direct message with the InsightConnect app:

* `icon-start`

Or, in a channel including the app:

* `@Rapid7 InsightConnect icon-start`

```
You may want to include some instructions about `icon-help` in here as well

2020-11-30 19:12 UTC, ncramer-r7 commented on workflows/Find_InsightConnect_Resources_from_Slack/help.md
> +
You may want to include some instruction on `icon-help` in here as well. Ex:

```
To seek further help on your InsightConnect journey, send a direct message to your InsightConnect Slack app or @ the app in a channel starting with the command `icon-help`. 

Follow along with the interactive Slack buttons to find the resources best sorted to your needs.
```

2020-11-30 19:17 UTC, ncramer-r7 commented on workflows/Find_InsightConnect_Resources_from_Slack/Find_InsightConnect_Resources_from_Slack.icon
> +                "matchChannel": "",
```suggestion
                "matchChannel": "change_me",
```
We typically include this "change_me" input to notify the user to change the channel to fit their environment

2020-11-30 19:17 UTC, ncramer-r7 commented on workflows/Find_InsightConnect_Resources_from_Slack/Find_InsightConnect_Resources_from_Slack.icon
> +          "matchChannel": "",
```suggestion
                "matchChannel": "change_me",
```
Same comment as above

2020-11-30 19:19 UTC, ncramer-r7 requested changes
I love this workflow! Should help massively with the ICON onboarding experience. The workflow itself looks good to me, tried it out on my side and it is super sleek! I commented on a few things that we do for standardization, but other than that, looks great!

2020-12-01 20:27 UTC, ncramer-r7 approved these changes

2020-12-01 21:55 UTC, mhofert-r7 approved these changes

2020-12-01 21:58 UTC, merged