New Workflow - Enrich indicators with Recorded Future from IDR Alert
rapid7/insightconnect-workflows pull request #385
Opened 2020-12-02 16:32 UTC by dsliwinski-r7

New Workflow - Enrich indicators with Recorded Future from IDR Alert

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

<details>

```
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 93.221ms
```

<summary>
icon validate
</summary>
</details>

### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

![workflow1](https://user-images.githubusercontent.com/73613193/100901284-f7777400-34c3-11eb-9d64-bce50a25e3a9.png)
![workflow2](https://user-images.githubusercontent.com/73613193/100901358-03633600-34c4-11eb-8b06-1a5dd2bf7af0.png)
![workflow3](https://user-images.githubusercontent.com/73613193/100901362-052cf980-34c4-11eb-8a93-0d9e54200e9f.png)
![workflow4](https://user-images.githubusercontent.com/73613193/100901377-08c08080-34c4-11eb-8a5e-c51058ddfc23.png)
![workflow5](https://user-images.githubusercontent.com/73613193/100901381-09f1ad80-34c4-11eb-8a34-89c05d57bd6f.png)
![workflow6](https://user-images.githubusercontent.com/73613193/100901385-0b22da80-34c4-11eb-953c-2fcc2992a88b.png)

#### Job

![job1](https://user-images.githubusercontent.com/73613193/100901483-24c42200-34c4-11eb-820f-42e2577153da.png)
![job2](https://user-images.githubusercontent.com/73613193/100901489-25f54f00-34c4-11eb-9bb5-520cfa42421a.png)

#### Artifact

![idr_alert_summary](https://user-images.githubusercontent.com/73613193/100901513-2b529980-34c4-11eb-9f1a-c37959beb2e8.png)
![lookup_domain_output](https://user-images.githubusercontent.com/73613193/100901517-2d1c5d00-34c4-11eb-8d20-4314dc4004c7.png)

2020-12-02 22:39 UTC, jschipp-r7 commented on workflows/Enrich_Indicators_with_Recorded_Future_from_IDR_Alert/help.md
> +* InsightConnect License
```suggestion
```

2020-12-02 22:44 UTC, jschipp-r7 requested changes
We can remove the following two screenshots:

* workflows/Enrich_Indicators_with_Recorded_Future_from_IDR_Alert/screenshots/job.png
* workflows/Enrich_Indicators_with_Recorded_Future_from_IDR_Alert/screenshots/artifacts.png

And replace them with screenshots showing a successful workflow run in Slack with some of the output

2020-12-02 22:44 UTC, jschipp-r7 commented on workflows/Enrich_Indicators_with_Recorded_Future_from_IDR_Alert/help.md
> +* Login to InsightConnect, and “Import” the .icon file into the workflow builder
These first two lines can be replaced with

```suggestion
Import the workflow from the Rapid7 Extension Library and proceed through the Import Workflow wizard in InsightConnect. Import plugins, create or select connections, and rename the workflow as a part of the Import Workflow wizard as necessary.
```

2020-12-07 14:03 UTC, dsliwinski-r7 commented
> We can remove the following two screenshots:
> 
>     * workflows/Enrich_Indicators_with_Recorded_Future_from_IDR_Alert/screenshots/job.png
> 
>     * workflows/Enrich_Indicators_with_Recorded_Future_from_IDR_Alert/screenshots/artifacts.png
> 
> 
> And replace them with screenshots showing a successful workflow run in Slack with some of the output

Hi @jschipp-r7! This workflow is triggered by an IDR alert, so I can't run it in Slack. Do you want me to add a few steps in which the results will be posted on Slack (using Slack ChatOps) or do you want something else?

2020-12-07 17:47 UTC, jschipp-r7 commented
@dsliwinski-r7 ah, yes - show the successful output of the workflow then

2020-12-07 20:06 UTC, dsliwinski-r7 commented
@jschipp-r7 I've added screenshots showing the successful output of the workflow.

2020-12-10 21:30 UTC, jschipp-r7 requested changes
Can we improve the readability of the artifact card? and use bold for the keys


*Risk Summary*: 4 of 47 Risk Rules currently observed
*Risk Score*: 2


 and also format the larger object Evidence Details. You can do that with input templating.
https://docs.rapid7.com/insightconnect/format-strings-with-templates#template-print-all-json-object-items

```
{{#each [StepName].[JSON object variable]}}
{{#each .}}
  {{@key}} = {{.}}
{{/each}}
{{/each}}
```

Need to address this one
* https://github.com/rapid7/insightconnect-workflows/pull/385/files#r534531751

2020-12-11 14:49 UTC, dsliwinski-r7 commented
@jschipp-r7 Sorry about that. I was sure I had already solved it :)

I improved the readability of the artifacts and updated the screenshots.

2020-12-11 14:56 UTC, jschipp-r7 approved these changes

2020-12-11 14:57 UTC, merged