Lookup Vulnerable Hosts from Slack and Microsoft Teams Workflow Improvements
rapid7/insightconnect-workflows pull request #388
Opened 2020-12-02 19:35 UTC by dsliwinski-r7

Lookup Vulnerable Hosts from Slack and Microsoft Teams Workflow Improvements

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Slack

<details>

```
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 47.106ms
```

<summary>
icon validate
</summary>
</details>

Microsoft Teams

<details>

```
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 50.545ms
```

<summary>
icon validate
</summary>
</details>

### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

Slack

![workflow](https://user-images.githubusercontent.com/73613193/100921691-3239d600-34dd-11eb-8f4b-5a1d38e0c3bd.png)
![workflow1](https://user-images.githubusercontent.com/73613193/100921701-3534c680-34dd-11eb-85bc-19c7a5c13325.png)
![workflow2](https://user-images.githubusercontent.com/73613193/100921705-3665f380-34dd-11eb-9dce-7619fd93bb5c.png)
![workflow3](https://user-images.githubusercontent.com/73613193/100921712-37972080-34dd-11eb-88db-1484749ed169.png)

Extract Vulnerability IDs from VulnDB Loop
![workflow4](https://user-images.githubusercontent.com/73613193/100921714-38c84d80-34dd-11eb-81ff-4004dc40d328.png)

Process Vulnerabilities Loop
![workflow5](https://user-images.githubusercontent.com/73613193/100921717-3960e400-34dd-11eb-8b3d-fdb1f47fc762.png)

Get Asset Information Loop
![workflow6](https://user-images.githubusercontent.com/73613193/100921718-3a921100-34dd-11eb-86ce-20522abba7b1.png)

Microsoft Teams

![workflow](https://user-images.githubusercontent.com/73613193/100920661-bab77700-34db-11eb-9642-7162dc6fe3d7.png)
![workflow1](https://user-images.githubusercontent.com/73613193/100921751-441b7900-34dd-11eb-97fa-bef3b9b70ee7.png)
![workflow2](https://user-images.githubusercontent.com/73613193/100921763-47166980-34dd-11eb-8e61-dae992b25b37.png)
![workflow3](https://user-images.githubusercontent.com/73613193/100921766-48479680-34dd-11eb-8c1b-ce038257a0c3.png)

Extract Vulnerability IDs from VulnDB Loop
![workflow4](https://user-images.githubusercontent.com/73613193/100921767-4978c380-34dd-11eb-8d01-c7bc3e583e71.png)

Process Vulnerabilities Loop
![workflow5](https://user-images.githubusercontent.com/73613193/100921772-4b428700-34dd-11eb-9e4d-cf11e6175544.png)

Get Asset Information Loop
![workflow6](https://user-images.githubusercontent.com/73613193/100921777-4c73b400-34dd-11eb-8d7b-f51f77666d5a.png)

#### Job

Slack

![slack_job1](https://user-images.githubusercontent.com/73613193/100921013-43361780-34dc-11eb-92ad-de7887e20c38.png)
![slack_job2](https://user-images.githubusercontent.com/73613193/100921017-44674480-34dc-11eb-8324-2b2e2a9d65d0.png)

Microsoft Teams

![teams_job1](https://user-images.githubusercontent.com/73613193/100921062-521cca00-34dc-11eb-90e1-38d4c702c700.png)
![teams_job2](https://user-images.githubusercontent.com/73613193/100921064-534df700-34dc-11eb-934e-8e2fdafc162a.png)

#### Artifact

Slack

![artifact](https://user-images.githubusercontent.com/73613193/100921123-682a8a80-34dc-11eb-9287-7cd438bc5f24.png)

Microsoft Teams

![artifact](https://user-images.githubusercontent.com/73613193/100921156-74aee300-34dc-11eb-804b-269ea3885545.png)

2020-12-02 22:48 UTC, jschipp-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Slack/help.md
> +Once the workflow has been imported, **first Slack step will need the channel name updated to suit your Slack environment!** Edit the input with the preset text of `change_me` in first Slack step in
```suggestion
Once the workflow has been imported, **first Slack step will need the channel name updated to suit your Slack environment!** Edit the input with the preset text of `change_me` in first Slack step in the workflow. There is also an optional Settings step which can be edited to change the maximum number of vulnerabilities and maximum hosts listed per vulnerability which are returned. The defaults are 50 vulnerabilities and 10 assets per vulnerability.
```

2020-12-02 22:49 UTC, jschipp-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Slack/help.md
> +* 1.1.0 - Use the automatic extraction functionality instead of 'Pattern Match' step to extract a vulnerability | Improve workflow messaging | Improve documentation | Update screenshots | Update Rapi
```suggestion
* 1.1.0 - Use the automatic extraction functionality instead of Pattern Match step to extract a vulnerability | Improve workflow messaging | Improve documentation | Update screenshots | Update Rapid7 InsightVM to version 4.8.1 | Update Type Converter to version 1.6.0
```

2020-12-02 22:50 UTC, jschipp-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md
> +Once the workflow has been imported, **first Microsoft Teams step will need the team name and channel name updated to suit your Teams environment!** Edit the input with the preset text of `change_me`
```suggestion
Once the workflow has been imported, **first Microsoft Teams step will need the team name and channel name updated to suit your Teams environment!** Edit the input with the preset text of `change_me` in first Microsoft Teams step in the workflow. There is also an optional Settings step which can be edited to change the maximum number of vulnerabilities and maximum hosts listed per vulnerability which are returned. The defaults are 50 vulnerabilities and 10 assets per vulnerability.
```

2020-12-02 22:52 UTC, jschipp-r7 requested changes
Needs included screenshots of successful workflow run from Slack and Teams (show chat output)

I know CVE extraction works but does the following still work per documentation?

* KB Number
* Nexpose ID

2020-12-03 18:16 UTC, dsliwinski-r7 commented
@jschipp-r7 I added screenshots of successful workflow run from Slack and Teams for Nexpose ID and KB Number.

2020-12-03 18:25 UTC, jschipp-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md
> +Once the workflow has been imported, **first Microsoft Teams step will need the team name and channel name updated to suit your Teams environment!** Edit the input with the preset text of `change_me`
```suggestion
Once the workflow has been imported, **the first Microsoft Teams step will need the team name and channel name updated to suit your Teams environment!** Edit the input with the preset text of `change_me` in first Microsoft Teams step in the workflow. There is also an optional Settings step which can be edited to change the maximum number of vulnerabilities and maximum hosts listed per vulnerability which are returned. The defaults are 50 vulnerabilities and 10 assets per vulnerability.
```

2020-12-03 18:26 UTC, jschipp-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Slack/help.md
> +Once the workflow has been imported, **first Slack step will need the channel name updated to suit your Slack environment!** Edit the input with the preset text of `change_me` in first Slack step in
```suggestion
Once the workflow has been imported, **the first Slack step will need the channel name updated to suit your Slack environment!** Edit the input with the preset text of `change_me` in first Slack step in the workflow. There is also an optional Settings step which can be edited to change the maximum number of vulnerabilities and maximum hosts listed per vulnerability which are returned. The defaults are 50 vulnerabilities and 10 assets per vulnerability.
```

2020-12-03 18:26 UTC, jschipp-r7 approved these changes

2020-12-03 18:26 UTC, merged