Purge Emails in O365 from Slack and Microsoft Teams Workflow Improvements
rapid7/insightconnect-workflows pull request #394
Opened 2020-12-07 16:16 UTC by dsliwinski-r7

Purge Emails in O365 from Slack and Microsoft Teams Workflow Improvements

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Slack

<details>

```
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 41.372ms
```

<summary>
icon validate
</summary>
</details>

Microsoft Teams

<details>

```
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 49.550999999999995ms
```

<summary>
icon validate
</summary>
</details>

### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

Slack

![workflow](https://user-images.githubusercontent.com/73613193/101375126-54ea3700-38af-11eb-8039-3607993df2c8.png)
![workflow1](https://user-images.githubusercontent.com/73613193/101375132-561b6400-38af-11eb-81d3-834ac68ca985.png)
![workflow2](https://user-images.githubusercontent.com/73613193/101375141-59165480-38af-11eb-9636-883fb21a3a7f.png)
![workflow3](https://user-images.githubusercontent.com/73613193/101375143-59aeeb00-38af-11eb-9856-6ba856d70814.png)

Microsoft Teams

![workflow](https://user-images.githubusercontent.com/73613193/101375262-764b2300-38af-11eb-8b73-a36a862c8e63.png)
![workflow1](https://user-images.githubusercontent.com/73613193/101375266-777c5000-38af-11eb-8620-9418d64e037b.png)
![workflow2](https://user-images.githubusercontent.com/73613193/101375274-79461380-38af-11eb-9150-8a71d06221d7.png)
![workflow3](https://user-images.githubusercontent.com/73613193/101375278-79deaa00-38af-11eb-900a-126b7943d0a2.png)

#### Job

Slack

![sample_command](https://user-images.githubusercontent.com/73613193/101375177-63385300-38af-11eb-9af3-d346133e5ac3.png)
![slack_flow1](https://user-images.githubusercontent.com/73613193/101375186-659aad00-38af-11eb-8562-27e9cf4bd919.png)
![slack_flow2](https://user-images.githubusercontent.com/73613193/101375195-66cbda00-38af-11eb-9f6f-4263cd931f34.png)
![slack_not_found](https://user-images.githubusercontent.com/73613193/101375200-67647080-38af-11eb-990a-206acaaacb3e.png)

Microsoft Teams

![teams_flow1](https://user-images.githubusercontent.com/73613193/101375317-8531d580-38af-11eb-90fb-97817fe4329f.png)
![teams_flow2](https://user-images.githubusercontent.com/73613193/101375319-86630280-38af-11eb-802c-2b1208387b27.png)
![teams_not_found](https://user-images.githubusercontent.com/73613193/101375322-86fb9900-38af-11eb-9681-6ffd272860da.png)

#### Artifact

<Insert Artifact Image Here>

2020-12-09 21:27 UTC, mrinehart-r7 requested changes

2020-12-09 21:27 UTC, mrinehart-r7 commented on workflows/Purge_Office_365_Emails_with_Microsoft_Teams/help.md
> -Search criteria can be 'body', 'subject', or 'from' lines in the email. For example:
Revert, keep the oxford comma :)

2020-12-09 21:27 UTC, mrinehart-r7 commented on workflows/Purge_Office_365_Emails_with_Microsoft_Teams/help.md
> -Any combination of 'body', 'subject', and 'from' can be used. At least one search item must be given.
Revert

2020-12-09 21:52 UTC, dsliwinski-r7 commented on workflows/Purge_Office_365_Emails_with_Microsoft_Teams/help.md
> -Any combination of 'body', 'subject', and 'from' can be used. At least one search item must be given.
@mrinehart-r7 Reverted :)

2020-12-10 21:17 UTC, jschipp-r7 approved these changes

2020-12-10 21:23 UTC, merged