MC-157 & MC-158 - Force Password Reset in Azure AD from Slack and Microsoft Teams - Workflow Improvements
rapid7/insightconnect-workflows pull request #401
Opened 2020-12-20 22:38 UTC by dmandyna-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

<details><summary>icon-validate ./Force_Password_Reset_in_Azure_AD_from_Microsoft_Teams</summary>

```
[*] Validating workflow at Force_Password_Reset_in_Azure_AD_from_Microsoft_Teams/

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 38.440000000000005ms
```
</details>

<details><summary>icon-validate ./Force_Password_Reset_in_Azure_AD_from_Slack</summary>

```
[*] Validating workflow at Force_Password_Reset_in_Azure_AD_from_Slack/

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 60.911ms
```
</details>

### Screenshots
<details><summary>Slack</summary>

#### Workflow Builder
![workflow1](https://user-images.githubusercontent.com/66844174/102726108-d90ed680-4313-11eb-8278-8d92ce147d3a.png)

#### Artifact
![artifact1](https://user-images.githubusercontent.com/66844174/102726111-dad89a00-4313-11eb-8713-f8aa42eaf880.png)

![artifact2](https://user-images.githubusercontent.com/66844174/102726112-dc09c700-4313-11eb-8b35-9f6cd8af90c2.png)

#### Messages
![slack1](https://user-images.githubusercontent.com/66844174/102726113-df04b780-4313-11eb-9405-206b327d19c6.png)

![slack2](https://user-images.githubusercontent.com/66844174/102726116-e035e480-4313-11eb-8f70-30301b237403.png)

</details>

<details><summary>Microsoft Teams</summary>

#### Workflow Builder
![workflow1](https://user-images.githubusercontent.com/66844174/102726123-e926b600-4313-11eb-90da-be7c10404acd.png)

#### Artifact
![artifact1](https://user-images.githubusercontent.com/66844174/102726124-ea57e300-4313-11eb-9c7f-986d4c98c117.png)

![artifact2](https://user-images.githubusercontent.com/66844174/102726126-eb891000-4313-11eb-86c8-f0028514de57.png)

#### Messages
![teams1](https://user-images.githubusercontent.com/66844174/102726127-ecba3d00-4313-11eb-8246-9d25f9901483.png)

![teams2](https://user-images.githubusercontent.com/66844174/102726130-ee840080-4313-11eb-8bc0-301453fc423f.png)

</details>

2020-12-21 19:01 UTC, ncramer-r7 requested changes
slack2.png still has your name @dmandyna-r7, but beyond that it looks good to me!

2020-12-21 21:09 UTC, dmandyna-r7 commented
Thanks! Not sure how I missed that one 🤦

2020-12-28 19:14 UTC, jmcadams-r7 approved these changes

2021-01-11 19:03 UTC, ncramer-r7 approved these changes

2021-01-19 20:22 UTC, merged