SOAR-2883 Update help and add filter to only allow assets scanned in last 30 days
rapid7/insightconnect-workflows pull request #402
Opened 2020-12-22 16:14 UTC by mhofert-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<Insert Workflow Image Here>

#### Job

<Insert Job Image Here>

#### Artifact

<Insert Artifact Image Here>
```

2020-12-22 19:48 UTC, mrinehart-r7 requested changes

2020-12-22 19:48 UTC, mrinehart-r7 commented on workflows/InsightVM_Top_25_Remediations_to_JIRA/help.md
> +This workflow checks assets scanned in the last 30 days. For each of the 25 assets with the highest vulnerability score, it creates one solution-based issue in JIRA per vulnerability found. These tic
```suggestion
This workflow checks assets scanned in the last 30 days. For each of the 25 assets with the highest vulnerability score, it creates one solution-based issue in Jira per vulnerability found. These tickets list the asset(s) affected. If there is already an issue open for a given remediation, the workflow updates the existing issue with a current list of impacted assets.
```

2020-12-22 19:48 UTC, mrinehart-r7 commented on workflows/InsightVM_Top_25_Remediations_to_JIRA/help.md
> +This workflow runs daily at 12:00 UTC. Adjust the time as necessary to suit your organization's needs by changing input in "Time in UTC." We recommend running this workflow during off-hours, as it is
```suggestion
This workflow runs daily at 12:00 UTC. Adjust the time as necessary to suit your organization's needs by changing input in "Time in UTC." It is recommended to run this workflow during off-hours, as it is data and CPU-intensive.
```

2020-12-22 19:48 UTC, mrinehart-r7 commented on workflows/InsightVM_Top_25_Remediations_to_JIRA/help.md
> +Note: Editing any of the following can significantly increase or decrease the time this workflow takes to run.
```suggestion
Note: Editing any of the following may negatively impact the runtime duration of the workflow.
```

2020-12-22 19:48 UTC, mrinehart-r7 commented on workflows/InsightVM_Top_25_Remediations_to_JIRA/help.md
> +To change the limit for number of assets scanned, go to the `Top 25 Remediations` step. Edit the `Asset Limit` field. To change the limit number of vulnerabilities found, you can edit the `Vulnerabil
```suggestion
To change the limit for number of assets scanned, go to the `Top 25 Remediations` step. Edit the `Asset Limit` field. The `Vulnerability Limit` field can be adjusted to limit the number of vulnerabilities.
```

2020-12-22 19:48 UTC, mrinehart-r7 commented on workflows/InsightVM_Top_25_Remediations_to_JIRA/help.md
> +By default, this workflow gets assets scanned in the last 30 days. To alter the limit from 30 days to a different number, edit the `Get assets scanned in the last 30 days` step. Find the input variab
```suggestion
By default, this workflow gets assets scanned in the last 30 days. To alter the limit from 30 days to a different number, edit the `Get Assets Scanned in the Last 30 Days` step. Find the input variable {"match":"all","filters":[{"field":"last-scan-date","operator":"is-within-the-last","value":30}]}. Change the number 30 within this variable to fit the needs of your organization.
```

2020-12-22 19:48 UTC, mrinehart-r7 commented on workflows/InsightVM_Top_25_Remediations_to_JIRA/InsightVM_Top_25_Remediations_to_JIRA.icon
> +            "name": "Extraction step",
```suggestion
            "name": "Extraction Step",
```

2021-01-05 21:39 UTC, ncramer-r7 approved these changes

2021-01-05 21:40 UTC, merged