Delete Inactive Assets with InsightVM workflows
rapid7/insightconnect-workflows pull request #405
Opened 2021-01-08 19:23 UTC by ewilson-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<Insert Workflow Image Here>

#### Job

<Insert Job Image Here>

#### Artifact

<Insert Artifact Image Here>
```

2021-01-08 20:06 UTC, jmcadams-r7 commented
Need to add the .icon (the workflows) to the commit.

2021-01-08 20:06 UTC, jmcadams-r7 requested changes
Please add the workflow files.

2021-01-20 17:08 UTC, ewilson-r7 reviewed
Changes have been reviewed and submitted

2021-01-20 17:54 UTC, jschipp-r7 commented on workflows/Delete_Inactive_Assets_with_InsightVM_from_Slack/help.md
> +1. Update the first step with the channel name to suit your Slack environment by editing the input with the preset text of `#change_me` to match the channel to monitor. The InsightConnect Slack chatb
```suggestion
1. Update the first step with the channel name to suit your Slack environment by editing the input with the preset text of `change_me` to match the channel to monitor. The InsightConnect Slack chatbot will need to be added to this channel. This workflow is configured by default so that it may only be started from this channel.
```

2021-01-20 17:55 UTC, jschipp-r7 commented on workflows/Delete_Inactive_Assets_with_InsightVM_from_Slack/workflow.spec.yaml
> +description: Quickly look up inactive assets in Rapid7 InsightVM from Slack, and make a decision to delete them. This workflow helps teams maintain a clean and accurate count of assets in their envir
```suggestion
description: Quickly look up inactive assets in Rapid7 InsightVM from Slack, and make a decision to delete them. This workflow helps teams maintain a clean and accurate count of assets in their environment through shared Slack channels.
```

2021-01-20 17:56 UTC, jschipp-r7 commented on workflows/Delete_Inactive_Assets_with_InsightVM_from_Slack/Delete_Inactive_Assets_with_InsightVM_from_Slack.icon
> +                "matchChannel": "#change_me",
```suggestion
                "matchChannel": "change_me",
```

2021-01-20 17:56 UTC, jschipp-r7 commented on workflows/Delete_Inactive_Assets_with_InsightVM_from_Slack/Delete_Inactive_Assets_with_InsightVM_from_Slack.icon
> +          "matchChannel": "#change_me",
```suggestion
          "matchChannel": "change_me",
```

2021-01-20 17:58 UTC, jschipp-r7 commented on workflows/Delete_Inactive_Assets_with_InsightVM_from_Teams/workflow.spec.yaml
> +  source_url: https://github.com/rapid7/insightconnect-workflows/tree/master/workflows/Delete_Inactive_Assets_with_InsightVM__from_Teams
```suggestion
  source_url: https://github.com/rapid7/insightconnect-workflows/tree/master/workflows/Delete_Inactive_Assets_with_InsightVM_from_Teams
```

2021-01-20 18:01 UTC, jschipp-r7 commented
Validation passed

```
$:Delete_Inactive_Assets_with_InsightVM_from_Slack jschipp$ icon-validate .
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 33.389ms
```

```
$ Delete_Inactive_Assets_with_InsightVM_from_Teams jschipp$ icon-validate .
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 37.19ms
```

2021-01-20 23:20 UTC, jschipp-r7 approved these changes

2021-01-20 23:20 UTC, merged