MC-115 & MC-116 - SonicWall Firewall - Check Host Status - Slack and Microsoft Teams
rapid7/insightconnect-workflows pull request #406
Opened 2021-01-15 23:16 UTC by dmandyna-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment
#### Icon-Validate

<details>

```
[*] Validating workflow at ./Check_Host_Block_Status_with_SonicWall_Firewall_from_Slack/

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 40.824ms
```

<summary>
icon-validate ./Check_Host_Block_Status_with_SonicWall_Firewall_from_Slack/
</summary>
</details>

<details>

```
[*] Validating workflow at ./Check_Host_Block_Status_with_SonicWall_Firewall_from_Microsoft_Teams/

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 40.268ms
```

<summary>
icon-validate ./Check_Host_Block_Status_with_SonicWall_Firewall_from_Microsoft_Teams/
</summary>
</details>

### Screenshots

<details>

#### Workflow Builder

##### Microsoft Teams
![workflow1](https://user-images.githubusercontent.com/66844174/104787450-79c3ab00-5787-11eb-8b42-f502b0f81228.png)

![workflow2](https://user-images.githubusercontent.com/66844174/104787452-7c260500-5787-11eb-91d7-6f4b9d5ce3a2.png)

##### Slack
![workflow1](https://user-images.githubusercontent.com/66844174/104787554-b099c100-5787-11eb-8e22-7b8ebd1c5fb7.png)

![workflow2](https://user-images.githubusercontent.com/66844174/104787556-b2638480-5787-11eb-8b86-32c10c19d367.png)

<summary>
Workflow Builder
</summary>
</details>
<details>

#### Messages

##### Microsoft Teams
![teams_message1](https://user-images.githubusercontent.com/66844174/104787462-82b47c80-5787-11eb-9a1d-5b57424eadba.png)

##### Slack
![slack_message1](https://user-images.githubusercontent.com/66844174/104787545-abd50d00-5787-11eb-9156-f4f02b4c6af6.png)

<summary>
Messages
</summary>
</details>

<details>

#### Artifact

##### Microsoft Teams
![artifact1](https://user-images.githubusercontent.com/66844174/104787505-9233c580-5787-11eb-89fb-f08139134b27.png)

##### Slack
![artifact1](https://user-images.githubusercontent.com/66844174/104787541-a677c280-5787-11eb-82d9-9a40d8dbaeb6.png)

<summary>
Artifact
</summary>
</details>

2021-01-19 17:53 UTC, ncramer-r7 commented on workflows/Check_Host_Block_Status_with_SonicWall_Firewall_from_Slack/workflow.spec.yaml
> +  keywords: [sonicwal, sonicos, firewall, slack, chatops, work_from_home]
```suggestion
  keywords: [sonicwall, sonicos, firewall, slack, chatops, work_from_home]
```

2021-01-19 17:57 UTC, ncramer-r7 commented on workflows/Check_Host_Block_Status_with_SonicWall_Firewall_from_Microsoft_Teams/workflow.spec.yaml
> +  keywords: [sonicwal, sonicos, firewall, teams, microsoft_teams, chatops, work_from_home]
```suggestion
  keywords: [sonicwall, sonicos, firewall, teams, microsoft_teams, chatops, work_from_home]
```

2021-01-19 17:58 UTC, ncramer-r7 requested changes
Other than the very small changes in the workflow.spec.yaml files, looks good to me!

2021-01-26 19:05 UTC, mrinehart-r7 requested changes

2021-01-26 19:05 UTC, mrinehart-r7 commented on workflows/Check_Host_Block_Status_with_SonicWall_Firewall_from_Slack/help.md
> +* The ability to see if an IP is currently blocked by the firewall
```suggestion
* The ability to see if an IP address is currently blocked by the firewall
```

2021-01-28 22:15 UTC, dmandyna-r7 commented
Hey @mrinehart-r7 / @ncramer-r7!
I've applied all the suggestions, thank you for the review! 😃

2021-01-29 16:59 UTC, mrinehart-r7 approved these changes

2021-01-29 18:46 UTC, ncramer-r7 approved these changes

2021-02-02 23:38 UTC, merged