MC-127 - Office 365 Analysis Workflow Improvements
rapid7/insightconnect-workflows pull request #409
Opened 2021-01-21 22:19 UTC by dmandyna-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

<details><summary>icon-validate ./Force_Password_Reset_in_Azure_AD_from_Microsoft_Teams</summary>

```
[*] Validating workflow at .\Office_365_Analysis\

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow failed validation! The following validation errors occurred:

Validator "WorkflowDirectoryNameMatchValidator" failed!
        Cause: Workflow directory name does not match the workflow filename!

----
[*] Total time elapsed: 111.189ms
```
</details>

<details><summary>Screenshots</summary>

#### Workflow Builder
![workflow1](https://user-images.githubusercontent.com/66844174/105419330-72444c00-5c36-11eb-8399-8212540d3423.png)

![workflow2](https://user-images.githubusercontent.com/66844174/105419333-73757900-5c36-11eb-8d89-b027d43808d7.png)

![workflow3](https://user-images.githubusercontent.com/66844174/105419337-753f3c80-5c36-11eb-81ca-9e777783c877.png)

![workflow4](https://user-images.githubusercontent.com/66844174/105419344-76706980-5c36-11eb-9f97-ce51f20a3da9.png)

![workflow5](https://user-images.githubusercontent.com/66844174/105419349-77a19680-5c36-11eb-8b6a-acc85ef93842.png)

![workflow6](https://user-images.githubusercontent.com/66844174/105419351-796b5a00-5c36-11eb-91c0-45c05b12d211.png)

#### Artifact
![artifact1](https://user-images.githubusercontent.com/66844174/105419356-7c664a80-5c36-11eb-921e-87ea5febc8fa.png)

![artifact2](https://user-images.githubusercontent.com/66844174/105419358-7cfee100-5c36-11eb-9eb6-6821a4fc2458.png)

#### Messages
![notification1](https://user-images.githubusercontent.com/66844174/105419362-80926800-5c36-11eb-89dc-2e7c5df7989b.png)

</details>

2021-01-25 16:24 UTC, ncramer-r7 reviewed
VERY minor thing, but there is a reference to Jon Schipp in an artifact screenshot. Everything looks good though, so I'll approve after that is sanitized!

2021-01-25 18:02 UTC, dmandyna-r7 commented
Thanks for picking this up, I've updated the screenshot now.

2021-01-25 18:24 UTC, ncramer-r7 approved these changes

2021-01-26 16:54 UTC, mrinehart-r7 requested changes
Few minor changes. Workflow validation is also failing for some reason.

2021-01-26 16:54 UTC, mrinehart-r7 commented on workflows/Office_365_Analysis/Office_365_Analysis.icon
> +                "content": "# Remediation Goes Here\n\n(this artifact can be removed)\n\nAt this point in the workflow, we've established we have a malicious email. \n\nRemediation steps go on this b
```suggestion
                "content": "# Remediation Goes Here\n\n(this artifact can be removed)\n\nAt this point in the workflow, we've established we have a malicious email. \n\nRemediation steps go on this branch of the flow. They can be email notifications, Slack notifications for human follow up. Remediation can also go further and block the sender and delete the email from your organization. \n\nIn this example, I will send a notification via email, and use the Office Admin plugin to both delete the email and block the sender from our organization. "
```

2021-01-26 16:54 UTC, mrinehart-r7 commented on workflows/Office_365_Analysis/Office_365_Analysis.icon
> +                "content": "## Attached Email Analysis\n\n(This artifact can be removed) \n\nThis loop will analyze any each of the attached emails and look for any malicious indicators - these inclu
```suggestion
                "content": "## Attached Email Analysis\n\n(This artifact can be removed) \n\nThis loop will analyze any each of the attached emails and look for any malicious indicators - these include any malicious URLs found within these emails, any attached files to these emails and if the email comes from a domains that is younger than 30 days. These will be the best indicators of a suspicious email. If any are found this email will be marked as malicious. "
```

2021-01-26 16:54 UTC, mrinehart-r7 commented on workflows/Office_365_Analysis/help.md
> +Once the workflow has been imported. **update the first step with the mailbox and subject to suit your environment** by editing the input with the preset text of `change_me`.
```suggestion
Once the workflow has been imported, **update the first step with the mailbox and subject to suit your environment** by editing the input with the preset text of `change_me`.
```

2021-01-26 16:58 UTC, dmandyna-r7 commented
> Few minor changes. Workflow validation is also failing for some reason.

Hey @mrinehart-r7,

The workflow validation is failing because the name of the folder where we store the workflow is not the same as workflow filename. Let me know if that's fine as it is (I didn't change any file/folder names as part of this ticket), or if you would like me to change either the folder name or the workflow file name (if so, let me know which one to change) 🙂 

Thank you!

2021-01-26 19:58 UTC, jschipp-r7 approved these changes

2021-01-26 19:58 UTC, jschipp-r7 commented
> > Few minor changes. Workflow validation is also failing for some reason.
> 
> Hey @mrinehart-r7,
> 
> The workflow validation is failing because the name of the folder where we store the workflow is not the same as workflow filename. Let me know if that's fine as it is (I didn't change any file/folder names as part of this ticket), or if you would like me to change either the folder name or the workflow file name (if so, let me know which one to change) 🙂
> 
> Thank you!

Looks like the name is the same (requirement) but the title is different so we should be good here.

2021-01-26 19:59 UTC, merged