[SOAR-4029] - Find_Indicator_in_DNS_Logs_with_InsightIDR_from_Slack
rapid7/insightconnect-workflows pull request #411
Opened 2021-01-28 19:33 UTC by jmcadams-r7

## Description: 

This PR adds the following WF:
SOAR-4029

## Validation: 
```
RMT-MBP-5357:Find_Indicator_In_DNS_Logs_with_InsightIDR_from_Slack jmcadams$ icon-validate .
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 24.284ms
```

![slack_message_found](https://user-images.githubusercontent.com/44783688/106189108-75c36000-616d-11eb-911a-944ba13e77c9.png)
![slack_message_not_found](https://user-images.githubusercontent.com/44783688/106189110-765bf680-616d-11eb-9c6e-10ad714f1cf9.png)
![workflow1](https://user-images.githubusercontent.com/44783688/106189112-765bf680-616d-11eb-9edb-88f274f6ac0a.png)
![workflow2](https://user-images.githubusercontent.com/44783688/106189113-76f48d00-616d-11eb-879b-c5771bd09786.png)

2021-02-01 17:04 UTC, jschipp-r7 requested changes

2021-02-01 17:04 UTC, jschipp-r7 commented on workflows/Find_Indicator_in_DNS_Logs_with_InsightIDR_from_Slack/workflow.spec.yaml
> +title: "Find Indicator in DNS Logs with InsightIDR from Slack"
Recommend renaming workflow and all references

```suggestion
title: "Hunt for Threat Indicators in InsightIDR DNS logs from Slack"
```

2021-02-01 17:04 UTC, jschipp-r7 commented on workflows/Find_Indicator_in_DNS_Logs_with_InsightIDR_from_Slack/help.md
> +Lookup suspicious URLs in IDR DNS Query logs with a simple slack command.
```suggestion
Lookup suspicious URLs or domains in IDR DNS Query logs with a simple slack command.
```

2021-02-01 17:04 UTC, jschipp-r7 commented on workflows/Find_Indicator_in_DNS_Logs_with_InsightIDR_from_Slack/help.md
> +* **Quickly analyze the scope of a malicious URL** - Quickly find out how many of your users were affected by a malicious URL
```suggestion
* **Quickly analyze the scope of a malicious URL** - Quickly find out how many of your users were affected by a malicious URL or domain
```

2021-02-01 17:04 UTC, jschipp-r7 commented on workflows/Find_Indicator_in_DNS_Logs_with_InsightIDR_from_Slack/help.md
> +Lookup suspicious URLs in IDR DNS Query logs with a simple slack command.
Also, document how we match either URL or domain so the user understands how it works

2021-02-02 15:24 UTC, cstuart-r7 approved these changes
LGTM

2021-02-02 15:50 UTC, jschipp-r7 commented on workflows/Hunt_for_Threats_in_DNS_Logs_with_InsightIDR_from_Slack/help.md
> +Lookup suspicious domains in IDR DNS Query logs with a simple slack command.
```suggestion
Lookup suspicious domains in IDR DNS Query logs with a simple slack command. This workflow accepts domains and URLs as input.
```

2021-02-02 15:53 UTC, jschipp-r7 commented on workflows/Hunt_for_Threats_in_DNS_Logs_with_InsightIDR_from_Slack/help.md
> +
```suggestion

`@Rapid7 InsightConnect get-logs https://aadroid.net`

```

2021-02-02 15:54 UTC, jschipp-r7 approved these changes

2021-02-02 15:55 UTC, merged