Update Lookup Vulnerable Hosts from Slack to use Parameters
rapid7/insightconnect-workflows pull request #412
Opened 2021-02-12 14:23 UTC by cmchugh-r7

## Requirements

### Checklist
- [x] Workflow verified as working in a test
- [x] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [x] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [x] Workflow includes a detailed Description
- [x] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [x] Triggers, Decisions, and other workflow steps include descriptions where needed
- [x] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [x] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] **TODO update with standardized param instructions** `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [x] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

![Screen Shot 2021-02-12 at 9 21 46 AM](https://user-images.githubusercontent.com/35234462/107779704-bdbcb800-6d13-11eb-8b28-16e33e0339c0.png)

![Screen Shot 2021-02-12 at 9 22 19 AM](https://user-images.githubusercontent.com/35234462/107779776-d2994b80-6d13-11eb-8727-bcffff820684.png)

#### Workflow Builder

![workflow](https://user-images.githubusercontent.com/35234462/107779519-70404b00-6d13-11eb-8630-8154555f3dfd.png)

#### Job

![Screen Shot 2021-02-12 at 9 22 55 AM](https://user-images.githubusercontent.com/35234462/107779825-e6dd4880-6d13-11eb-9200-dde67202b002.png)

#### Artifact

![Screen Shot 2021-02-12 at 9 23 26 AM](https://user-images.githubusercontent.com/35234462/107779870-f8265500-6d13-11eb-8ad3-df888d333eae.png)

2021-02-12 14:28 UTC, cmchugh-r7 commented
Waiting on finalized language for parameter setup instructions, then will update help+description. Cannot be merged til param release.

2021-02-16 14:57 UTC, malolans-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Slack/Lookup_Vulnerable_Hosts_From_Slack.icon
> +              "channel name": {
Should we have descriptions for the parameters?

2021-02-16 15:25 UTC, cmchugh-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Slack/Lookup_Vulnerable_Hosts_From_Slack.icon
> +              "channel name": {
added!

2021-02-16 19:55 UTC, jschipp-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Slack/help.md
> +* 2.0.0 - Use Workflow Parameters to configure Slack channel name, max vulnerabilities, and max hosts values (and remove the Settings step); Update CSV to version 1.1.6; Update Type Converter to 1.7.
Style is `|` in the Changelog 

```suggestion
* 2.0.0 - Use Workflow Parameters to configure Slack channel name, max vulnerabilities, and max hosts values (and remove the Settings step) | Update CSV to version 1.1.6 | Update Type Converter to 1.7.0
```

2021-02-16 20:01 UTC, cmchugh-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Slack/help.md
> +* 2.0.0 - Use Workflow Parameters to configure Slack channel name, max vulnerabilities, and max hosts values (and remove the Settings step); Update CSV to version 1.1.6; Update Type Converter to 1.7.
ahh thanks Jon

2021-02-16 21:07 UTC, cmchugh-r7 commented
Validator is failing due to diff between description and spec, however as per [this thread](https://rapid7.slack.com/archives/C6GJ6F420/p1613506809051900) this check is getting removed and we should keep the "short" description in the yaml

2021-02-17 14:55 UTC, jnikitin-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Slack/Lookup_Vulnerable_Hosts_From_Slack.icon
> +                "description": "The maximum number of hosts listed per vulnerability (recommended default is 10)"
I was maybe thinking of adding "affected hosts", but idk if the change is really needed.

2021-02-17 14:56 UTC, jnikitin-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Slack/help.md
> +* `Slack Channel`:  the Slack channel name in your environment where the workflow should be triggered and respond
two spaces here

2021-02-17 16:43 UTC, cmchugh-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Slack/Lookup_Vulnerable_Hosts_From_Slack.icon
> +                "description": "The maximum number of hosts listed per vulnerability (recommended default is 10)"
ah thats a good idea, i like that, i'll update

2021-02-17 19:00 UTC, mrinehart-r7 requested changes

2021-02-17 19:00 UTC, mrinehart-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Slack/help.md
> +* `Slack Channel`: the Slack channel name in your environment where the workflow should be triggered and respond
```suggestion
* `Slack Channel`: The Slack channel name in your environment where the workflow should be triggered and respond
```

2021-02-17 19:00 UTC, mrinehart-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Slack/help.md
> +* `Max Hosts`: the maximum number of hosts listed per vulnerability (recommended default is 10)
```suggestion
* `Max Hosts`: The maximum number of hosts listed per vulnerability (recommended default is 10)
```

2021-02-17 19:00 UTC, mrinehart-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Slack/help.md
> +* `Max Vulnerabilities`: the maximum number of returned vulnerabilities (recommended default is 50)
```suggestion
* `Max Vulnerabilities`: The maximum number of returned vulnerabilities (recommended default is 50)
```

2021-02-17 19:17 UTC, cmchugh-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Slack/help.md
> +* `Max Vulnerabilities`: the maximum number of returned vulnerabilities (recommended default is 50)
all updated!

2021-02-18 14:36 UTC, jschipp-r7 submitted a review, later dismissed

2021-02-18 22:55 UTC, smorrison-r7 requested changes
Aligning Version Formatting

2021-02-19 20:19 UTC, mrinehart-r7 requested changes

2021-02-19 20:19 UTC, mrinehart-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Slack/workflow.spec.yaml
> +version: 2.0.0
```suggestion
version: 1.2.0
```
Mismatch between changelog and this version

2021-02-19 20:20 UTC, mrinehart-r7 submitted a review, later dismissed

2021-02-19 20:25 UTC, smorrison-r7 approved these changes

2021-02-19 20:33 UTC, mrinehart-r7 approved these changes

2021-02-22 16:09 UTC, malolans-r7 approved these changes

2021-02-22 16:09 UTC, merged