SOAR-4446 - Update Enrich Indicators with OSINT from Microsoft Teams to use parameters
rapid7/insightconnect-workflows pull request #414
Opened 2021-02-16 19:18 UTC by malolans-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<Insert Workflow Image Here>

#### Job

<Insert Job Image Here>

#### Artifact

<Insert Artifact Image Here>
```

2021-02-16 20:33 UTC, jmcadams-r7 approved these changes

2021-02-16 20:50 UTC, cmchugh-r7 requested changes
the Setup help needs to be updated to instruct on using params for channel name. Also i think @smorrison-r7 has standard language we should be using

2021-02-17 18:56 UTC, mrinehart-r7 requested changes

2021-02-17 18:56 UTC, mrinehart-r7 commented on workflows/Enrich_Indicators_with_OSINT_from_Microsoft_Teams/workflow.spec.yaml
> +description: "# Description\n\nThreat Intelligence doesn’t have to come with a cost. This workflow uses open-source intelligence (OSINT) to perform domain lookups, header analysis, hash analysis, and
This should exist in the help.md, not the description in the yaml file

2021-02-22 16:21 UTC, mrinehart-r7 requested changes

2021-02-22 16:21 UTC, mrinehart-r7 commented on workflows/Enrich_Indicators_with_OSINT_from_Microsoft_Teams/help.md
> +* `team name`:  The Microsoft Teams team name in your environment where the workflow should be triggered and respond
```suggestion
* `team name`: The Microsoft Teams team name in your environment where the workflow should be triggered and respond
```

2021-02-22 16:21 UTC, mrinehart-r7 approved these changes

2021-02-22 16:24 UTC, cmchugh-r7 approved these changes

2021-02-22 16:24 UTC, merged