Update automated indicator enrichment to use parameters
rapid7/insightconnect-workflows pull request #416
Opened 2021-02-16 23:37 UTC by smorrison-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [x ] Workflow verified as working in a test
- [ x] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [x ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ x] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<Insert Workflow Image Here>

#### Job

<Insert Job Image Here>

#### Artifact

<Insert Artifact Image Here>
```

2021-02-17 18:29 UTC, mrinehart-r7 requested changes

2021-02-17 18:29 UTC, mrinehart-r7 commented on workflows/Automated_Indicator_Enrichment/help.md
> +This workflow leverages insightConnect's Parameters feature. This feature allows variables used multiple times throughout a workflow to be entered once and then referenced throughout the workflow.
```suggestion
This workflow leverages InsightConnect's Parameters feature. This feature allows variables used multiple times throughout a workflow to be entered once and then referenced throughout the workflow. 
```

2021-02-17 18:29 UTC, mrinehart-r7 commented on workflows/Automated_Indicator_Enrichment/help.md
> +* `Slack Channel`:  the Slack channel name in your environment where the workflow should be triggered and respond
```suggestion
* `Slack Channel`: The Slack channel name in your environment where the workflow should be triggered and respond
```

2021-02-17 18:29 UTC, mrinehart-r7 commented on workflows/Automated_Indicator_Enrichment/help.md
> +* 1.2.0 - Leverage Parameters Feature | Update plugins
```suggestion
* 1.2.0 - Leverage Parameters Feature | Update AbuseIPDB, VirusTotal, Whois, and Type Converter plugins
```
You'll also need to update the plugins table in the help.md to correspond to the version updates

2021-02-18 20:50 UTC, jnikitin-r7 commented on workflows/Automated_Indicator_Enrichment/help.md
you need to edit the versions below, I think

2021-02-22 16:23 UTC, mrinehart-r7 requested changes
Need to update plugin versions in the Technical Details section

2021-02-22 16:47 UTC, smorrison-r7 reviewed
Updated Plugin Versions

2021-02-22 16:56 UTC, mrinehart-r7 requested changes

2021-02-22 16:56 UTC, mrinehart-r7 commented on workflows/Automated_Indicator_Enrichment/help.md
> +|Type Converter|1.7.0|
```suggestion
|Type Converter|1.7.0|1|
```

2021-02-22 16:56 UTC, mrinehart-r7 commented on workflows/Automated_Indicator_Enrichment/help.md
> +|AbuseIPDB|5.0.6|
```suggestion
|AbuseIPDB|5.0.6|1|
```

2021-02-22 16:56 UTC, mrinehart-r7 commented on workflows/Automated_Indicator_Enrichment/help.md
> +|VirusTotal|6.0.4|
```suggestion
|VirusTotal|6.0.4|1|
```

2021-02-22 16:56 UTC, mrinehart-r7 commented on workflows/Automated_Indicator_Enrichment/help.md
> +|WHOIS|3.0.1|
```suggestion
|WHOIS|3.0.1|1|
```

2021-02-22 16:59 UTC, mrinehart-r7 requested changes

2021-02-22 16:59 UTC, mrinehart-r7 commented on workflows/Automated_Indicator_Enrichment/workflow.spec.yaml
> +version: 1.2.0
```suggestion
version: 2.0.0
```

2021-02-22 18:02 UTC, merged