[SOAR-4451]: Lookup Vulnerable Hosts from Teams to use parameters (TRY 2)
rapid7/insightconnect-workflows pull request #417
Opened 2021-02-17 14:42 UTC by jnikitin-r7

https://issues.corp.rapid7.com/browse/SOAR-4451

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [x] Workflow verified as working in a test
- [x] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [x] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [x] Workflow includes a detailed Description
- [x] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [x] Triggers, Decisions, and other workflow steps include descriptions where needed
- [x] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [x] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [x] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [x] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

I updated to use workflow parameters for max hosts, max vulns, team name, and channel name.

### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

<img width="911" alt="image" src="https://user-images.githubusercontent.com/75641395/108123809-6b153000-7074-11eb-8cef-c80ed4170cf9.png">

<img width="484" alt="image" src="https://user-images.githubusercontent.com/75641395/108123856-78321f00-7074-11eb-813d-7c39b0fc9b75.png">

<img width="831" alt="image" src="https://user-images.githubusercontent.com/75641395/108124001-add70800-7074-11eb-8745-0debd92f06f1.png">

2021-02-17 14:43 UTC, malolans-r7 commented
Should we have a consistent description for MS team name and MS channel name parameter? @smorrison-r7

2021-02-17 14:52 UTC, jnikitin-r7 commented
> Should we have a consistent description for MS team name and MS channel name parameter? @smorrison-r7

I would love something better. I tried to be specific, not "Microsoft Team channel name", but something that tells people that its the specific and only channel name where commands will be enabled in.

2021-02-17 14:56 UTC, malolans-r7 commented
> > Should we have a consistent description for MS team name and MS channel name parameter? @smorrison-r7
> 
> I would love something better. I tried to be specific, not "Microsoft Team channel name", but something that tells people that its the specific and only channel name where commands will be enabled in.

I used `The Microsoft Teams team name where the workflow will be triggered and respond` and `The Microsoft Teams channel name where the workflow will be triggered and respond`

2021-02-17 16:47 UTC, jnikitin-r7 commented
> > > Should we have a consistent description for MS team name and MS channel name parameter? @smorrison-r7
> > 
> > 
> > I would love something better. I tried to be specific, not "Microsoft Team channel name", but something that tells people that its the specific and only channel name where commands will be enabled in.
> 
> I used `The Microsoft Teams team name where the workflow will be triggered and respond` and `The Microsoft Teams channel name where the workflow will be triggered and respond`

all set

2021-02-17 18:20 UTC, mrinehart-r7 requested changes

2021-02-17 18:20 UTC, mrinehart-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md
> +This workflow leverages insightConnect's Parameters feature. This feature allows variables used multiple times throughout a workflow to be entered once and then referenced throughout the workflow. To
```suggestion
This workflow leverages InsightConnect's Parameters feature. This feature allows variables used multiple times throughout a workflow to be entered once and then referenced throughout the workflow. To begin, select "Parameters" either from the Workflow home page or from the Builder to begin configuration.
```
Match the above paragraph w/r/t ICON branding

2021-02-17 18:20 UTC, mrinehart-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md
> +* `Team Name`:  the Microsoft Teams team name in your environment where the workflow should be triggered and respond
```suggestion
* `Team Name`: The Microsoft Teams team name in your environment where the workflow should be triggered and respond
```

2021-02-17 18:20 UTC, mrinehart-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md
> +* `Channel Name`:  the Microsoft Teams channel name in your environment where the workflow should be triggered and respond (the channel should exist in the aforementioned team)
```suggestion
* `Channel Name`: The Microsoft Teams channel name in your environment where the workflow should be triggered and respond (the channel should exist in the aforementioned team)
```

2021-02-17 18:20 UTC, mrinehart-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md
> +* `Max Hosts`: the maximum number of hosts listed per vulnerability (recommended default is 10)
```suggestion
* `Max Hosts`: The maximum number of hosts listed per vulnerability (recommended default is 10)
```

2021-02-17 18:20 UTC, mrinehart-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md
> +* `Max Vulnerabilities`: the maximum number of returned vulnerabilities (recommended default is 50)
```suggestion
* `Max Vulnerabilities`: The maximum number of returned vulnerabilities (recommended default is 50)
```

2021-02-17 18:20 UTC, mrinehart-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md
> +To configure the parameters, select "Parameters" either from the Workflow Control Panel page or from the Workflow Builder. Once configured, workflow setup is complete.
```suggestion
To configure the parameters, select "Parameters" either from the Workflow Control Panel page or from the Workflow Builder. Once configured, workflow setup is complete.

```

2021-02-17 18:20 UTC, mrinehart-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md
> +To configure the parameters, select "Parameters" either from the Workflow Control Panel page or from the Workflow Builder. Once configured, workflow setup is complete.
Also, this paragraph is a bit redundant with https://github.com/rapid7/insightconnect-workflows/pull/417/files#diff-3049d7ff2243a491195521158c9996cbabb0058048cb6addba1a8f30e23f8b4aR27

2021-02-17 20:04 UTC, jnikitin-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md
> +* `Team Name`:  the Microsoft Teams team name in your environment where the workflow should be triggered and respond
all set

2021-02-17 20:04 UTC, jnikitin-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md
> +* `Channel Name`:  the Microsoft Teams channel name in your environment where the workflow should be triggered and respond (the channel should exist in the aforementioned team)
all set

2021-02-17 20:05 UTC, jnikitin-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md
> +* `Max Hosts`: the maximum number of hosts listed per vulnerability (recommended default is 10)
all set

2021-02-17 20:05 UTC, jnikitin-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md
> +* `Max Vulnerabilities`: the maximum number of returned vulnerabilities (recommended default is 50)
all set

2021-02-17 20:05 UTC, jnikitin-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md
> +This workflow leverages insightConnect's Parameters feature. This feature allows variables used multiple times throughout a workflow to be entered once and then referenced throughout the workflow. To
all set

2021-02-17 20:14 UTC, jnikitin-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md
> +To configure the parameters, select "Parameters" either from the Workflow Control Panel page or from the Workflow Builder. Once configured, workflow setup is complete.
I believe Charlotte's PR has the same wording? should we just delete this part? if so, I can coordinate with her.

2021-02-18 14:35 UTC, jschipp-r7 approved these changes

2021-02-18 15:53 UTC, jnikitin-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/workflow.spec.yaml
>  description: Lookup vulnerability details and identify affected hosts with a Microsoft Teams message message trigger.
@mrinehart-r7 Malo and I noticed this description today? `Microsoft Teams message message trigger`, should we change this to `Microsoft Teams message trigger`?

2021-02-18 17:33 UTC, mrinehart-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/workflow.spec.yaml
>  description: Lookup vulnerability details and identify affected hosts with a Microsoft Teams message message trigger.
Yes - no need for two messages :)

2021-02-18 19:15 UTC, jnikitin-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/help.md
> +To configure the parameters, select "Parameters" either from the Workflow Control Panel page or from the Workflow Builder. Once configured, workflow setup is complete.
all set, deleted

2021-02-18 19:15 UTC, jnikitin-r7 commented on workflows/Lookup_Vulnerable_Hosts_From_Teams/workflow.spec.yaml
>  description: Lookup vulnerability details and identify affected hosts with a Microsoft Teams message message trigger.
fixed, all set

2021-02-22 16:25 UTC, mrinehart-r7 approved these changes

2021-02-22 16:25 UTC, malolans-r7 approved these changes

2021-02-22 16:25 UTC, merged