MC-584, MC-585, MC-586 - Recorded Future Workflows Update
rapid7/insightconnect-workflows pull request #456
Opened 2021-07-16 23:04 UTC by dmandyna-r7

## Requirements

Updated Look_Up_Hashes_with_Recorded_Future, Look_Up_IPs_with_Recorded_Future and Look_Up_URLs_with_Recorded_Future workflows to use the latest version of `Recorded Future` plugin - 5.0.1 and added screenshots as they were missing.

Jira URLs:
https://issues.corp.rapid7.com/browse/MC-584
https://issues.corp.rapid7.com/browse/MC-584 

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<Insert Workflow Image Here>

#### Job

<Insert Job Image Here>

#### Artifact

<Insert Artifact Image Here>
```

2021-11-17 21:02 UTC, pmara-r7 requested changes

2021-11-17 21:06 UTC, pmara-r7 submitted a review, later dismissed

2021-11-18 18:28 UTC, mrinehart-r7 requested changes

2021-11-18 18:28 UTC, mrinehart-r7 commented on workflows/Look_Up_IPs_with_Recorded_Future/Look_Up_IPs_with_Recorded_Future.icon
> +                "content": "{{#if [d62f8ffc-10af-4d67-819a-69e437358a52].[$success]}}\n**RecordedFuture IP Lookup Results for {{[d62f8ffc-10af-4d67-819a-69e437358a52].[data].[entity].[name]}}**\n**Qu
```suggestion
                "content": "{{#if [d62f8ffc-10af-4d67-819a-69e437358a52].[$success]}}\n**RecordedFuture IP Lookup Results for {{[d62f8ffc-10af-4d67-819a-69e437358a52].[data].[entity].[name]}}**\n**Quick Lookup:** {{[d62f8ffc-10af-4d67-819a-69e437358a52].[data].[intelCard]}}\n\n**Risk Score:** {{[d62f8ffc-10af-4d67-819a-69e437358a52].[data].[risk].[score]}} (out of 100)\n**Risk Summary:** {{[d62f8ffc-10af-4d67-819a-69e437358a52].[risk].[riskSummary]}}\n**Risk Criticality:** {{[d62f8ffc-10af-4d67-819a-69e437358a52].[data].[risk].[riskSummary]}}\n\n**ASN:** {{[d62f8ffc-10af-4d67-819a-69e437358a52].[data].[location].[asn]}}\n**Country:** {{[d62f8ffc-10af-4d67-819a-69e437358a52].[data].[location].[location].[country]}}\n**Organization Name:** {{[d62f8ffc-10af-4d67-819a-69e437358a52].[data].[location].[organization]}}\n**CIDR:** {{[d62f8ffc-10af-4d67-819a-69e437358a52].[data].[entity].[name]}}\n{{else}}\n**RecordedFuture IPs Lookup for: {{[ae3964ca-f924-4b71-935a-355f257baa50].[$item].[ip]}} yielded no results**\n{{/if}}"
```

2021-11-18 18:32 UTC, mrinehart-r7 approved these changes

2021-11-18 18:56 UTC, pmara-r7 approved these changes

2021-11-18 18:56 UTC, merged