SOAR-6605 Unlock AD/LDAP User from Microsoft Teams
rapid7/insightconnect-workflows pull request #463
Opened 2021-08-24 14:23 UTC by pmara-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<Insert Workflow Image Here>

#### Job

<Insert Job Image Here>

#### Artifact

<Insert Artifact Image Here>
```

2021-08-24 15:10 UTC, mberezin-r7 reviewed
Once we get a second opinion on including time saved, I think this looks good to go.

2021-08-24 15:10 UTC, mberezin-r7 commented on workflows/Unlock_User_Account_in_Active_Directory_from_Microsoft_Teams/help.md
> +After locking down a user account, it may be convenient to allow administrators to unlock users account. The normal unlock account would require logging into the AD server and manually unlocking it.
```suggestion
After locking down a user account, it may be convenient to allow administrators to unlock users account. The normal unlock account would require logging into the AD server and manually unlocking it.
```

I lean toward suggesting that we do not provide specific numbers for time saved estimates, but I am not strongly committed to this and can easily be persuaded otherwise to keep it as is or with phrasing tweaks.

2021-08-25 16:44 UTC, mrinehart-r7 requested changes
For teams1.png, can you blur out the username using a tool like Photopea?

2021-08-25 16:44 UTC, mrinehart-r7 commented on workflows/Unlock_User_Account_in_Active_Directory_from_Microsoft_Teams/Unlock_User_Account_in_Active_Directory_from_Microsoft_Teams.icon
> +                "content": "Wrong arguments usage"
```suggestion
                "content": "Wrong arguments usage"
```
Can you change this to messaging that will help the user use the workflow properly?

2021-08-25 16:44 UTC, mrinehart-r7 commented on workflows/Unlock_User_Account_in_Active_Directory_from_Microsoft_Teams/help.md
> +
Let's update the workflow to use workflow parameters, and then change this paragraph to tell the user to configure parameters.

2021-08-25 16:45 UTC, mrinehart-r7 commented
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Executing validator WorkflowEncodingValidator
[*] Executing validator WorkflowParametersKeywordValidator
[*] Executing validator UseCaseValidator
[*] Executing validator UnapprovedKeywordsValidator
320
[*] Workflow successfully validated!

----
[*] Total time elapsed: 331.584ms

2021-08-30 14:51 UTC, mrinehart-r7 requested changes

2021-08-30 14:51 UTC, mrinehart-r7 commented on workflows/Unlock_User_Account_in_Active_Directory_from_Microsoft_Teams/Unlock_User_Account_in_Active_Directory_from_Microsoft_Teams.icon
> +                "description": "The Miscosoft Teams channel name where this workflow will take place"
```suggestion
                "description": "The Microsoft Teams channel name where this workflow will take place"
```

2021-08-30 14:51 UTC, mrinehart-r7 commented on workflows/Unlock_User_Account_in_Active_Directory_from_Microsoft_Teams/Unlock_User_Account_in_Active_Directory_from_Microsoft_Teams.icon
> +                "description": "Search base for your AD instance Users, E.G.\nOU=Users,DC=myorgname,DC=com"
```suggestion
                "description": "Search base for your AD instance users, e.g.\nOU=Users,DC=myorgname,DC=com"
```

2021-08-30 14:54 UTC, mrinehart-r7 requested changes

2021-08-30 14:54 UTC, mrinehart-r7 commented on workflows/Unlock_User_Account_in_Active_Directory_from_Microsoft_Teams/Unlock_User_Account_in_Active_Directory_from_Microsoft_Teams.icon
> +                "content": "Wrong arguments usage, Use !unlock-user-ad [username]"
```suggestion
                "content": "Wrong arguments usage, use !unlock-user-ad [username]"
```

2021-08-30 14:58 UTC, mrinehart-r7 requested changes

2021-08-30 14:58 UTC, mrinehart-r7 commented on workflows/Unlock_User_Account_in_Active_Directory_from_Microsoft_Teams/help.md
> +Once the workflow has been imported, you must edit the workflow paramaters to match you Teams channel and team name, as well as the search base for your Active directory/LDAP instance (see troublesho
```suggestion
Once the workflow has been imported, you must edit the workflow parameters to match your Teams channel and team name, as well as the search base for your Active Directory/LDAP instance (see troubleshooting for tips on setting search base). 
```

2021-08-30 14:58 UTC, mrinehart-r7 commented on workflows/Unlock_User_Account_in_Active_Directory_from_Microsoft_Teams/help.md
> +After configuring the Teams steps, activate the workflow in order to trigger it.
```suggestion
```

2021-08-30 17:28 UTC, mrinehart-r7 requested changes

2021-08-30 17:28 UTC, mrinehart-r7 commented on workflows/Unlock_User_Account_in_Active_Directory_from_Microsoft_Teams/help.md
> +After locking down a user account, it may be convenient to allow administrators to unlock users account. The normal unlock account would require logging into the AD server and manually unlocking it.
```suggestion
After locking down a user account, it may be convenient to allow administrators to unlock users accounts. The normal unlock account process would require logging into the AD server and manually unlocking it. This workflow allows a user to unlock an account via Microsoft Teams command.
```

2021-08-30 17:29 UTC, merged