SOAR-6604 Unlock User Account in AD/LDAP from Slack
rapid7/insightconnect-workflows pull request #464
Opened 2021-08-26 16:42 UTC by pmara-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<Insert Workflow Image Here>

#### Job

<Insert Job Image Here>

#### Artifact

<Insert Artifact Image Here>
```

2021-08-30 17:53 UTC, mrinehart-r7 requested changes

2021-08-30 17:53 UTC, mrinehart-r7 commented on workflows/Unlock_User_Account_in_Active_Directory_from_Slack/Unlock_User_Account_in_Active_Directory_from_Slack.icon
> +            "description": "Trigger for ",
```suggestion
            "description": "Trigger for ",
```
for...? 😆  Need to finish this sentence

2021-08-30 17:53 UTC, mrinehart-r7 commented on workflows/Unlock_User_Account_in_Active_Directory_from_Slack/Unlock_User_Account_in_Active_Directory_from_Slack.icon
> +            "continueOnFailure": false,
```suggestion
            "continueOnFailure": true,
```
This should be `true` so that if there is an Exception raised during plugin run, the downstream steps (alerting the user to the failure) will still execute.

2021-08-30 17:53 UTC, mrinehart-r7 commented on workflows/Unlock_User_Account_in_Active_Directory_from_Slack/Unlock_User_Account_in_Active_Directory_from_Slack.icon
> +                  "expressionText": "{{[6c7fb9bb-05c0-4ffe-aeec-ce59f0707155].[$success]}} = true"
```suggestion
                  "expressionText": "{{[6c7fb9bb-05c0-4ffe-aeec-ce59f0707155].[$success]}} = true AND {{[6c7fb9bb-05c0-4ffe-aeec-ce59f0707155].[success]}} = true"
```
`$success` just checks to make sure the step ran without raising an Exception, so you'll also want to check that the unlock itself was successful, otherwise the current logic might route the workflow incorrectly.

2021-08-30 17:53 UTC, mrinehart-r7 commented on workflows/Unlock_User_Account_in_Active_Directory_from_Slack/help.md
> +After locking down a user account, it may be convenient to allow administrators to unlock users account. The normal unlock account would require logging into the AD server and manually unlocking it.
```suggestion
After locking down a user account, it may be convenient to allow administrators to unlock users account. The normal unlock account would require logging into the AD server and manually unlocking it. This workflow allows a user to unlock an account via Slack command.
```

2021-08-30 17:53 UTC, mrinehart-r7 commented on workflows/Unlock_User_Account_in_Active_Directory_from_Slack/help.md
> +You may also optionally choose a slack channel name to exclusively activate this command from. Leave this blank to allow for any channel.
```suggestion
You may also optionally choose a Slack channel name to exclusively activate this command from. Leave this blank to allow for any channel.
```

2021-08-30 17:53 UTC, mrinehart-r7 commented on workflows/Unlock_User_Account_in_Active_Directory_from_Slack/help.md
> +If you have multiple "." in the address, split each into its own "DC" section.
```suggestion
OU=Users,DC=examplecompany,DC=com

If you have multiple "." in the address, split each into its own "DC" section. 
```

2021-09-01 17:49 UTC, pmara-r7 commented on workflows/Unlock_User_Account_in_Active_Directory_from_Slack/Unlock_User_Account_in_Active_Directory_from_Slack.icon
> +                  "expressionText": "{{[6c7fb9bb-05c0-4ffe-aeec-ce59f0707155].[$success]}} = true"
Wow! I didn't know this one...so success is a special step keyword?

2021-09-01 17:50 UTC, pmara-r7 commented on workflows/Unlock_User_Account_in_Active_Directory_from_Slack/Unlock_User_Account_in_Active_Directory_from_Slack.icon
> +            "description": "Trigger for ",
```suggestion
            "description": "Trigger for Slack message received",
```

2021-09-02 16:29 UTC, mrinehart-r7 commented
```
mrinehart@RMT-MBP-9709:~workflows/workflows|SOAR-6604-Unlock-ADLDAP-Slack ⇒  icon-validate Unlock_User_Account_in_Active_Directory_from_Slack
[*] Validating workflow at Unlock_User_Account_in_Active_Directory_from_Slack

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Executing validator WorkflowEncodingValidator
[*] Executing validator WorkflowParametersKeywordValidator
[*] Executing validator UseCaseValidator
[*] Executing validator UnapprovedKeywordsValidator
[*] Executing validator WorkflowPythonScriptUseValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 458.513ms
```

2021-09-02 16:29 UTC, mrinehart-r7 approved these changes

2021-09-02 16:30 UTC, mberezin-r7 approved these changes

2021-09-02 16:45 UTC, merged