SOAR-7243 Multi-Country Auth Workflow
rapid7/insightconnect-workflows pull request #480
Opened 2021-10-22 16:55 UTC by jrose-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [x] Workflow verified as working in a test
- [x] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [x] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [x] Workflow includes a detailed Description
- [x] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [x] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [x] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [x] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [x] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<Insert Workflow Image Here>

#### Job

<Insert Job Image Here>

#### Artifact

<Insert Artifact Image Here>
```

2021-11-02 14:13 UTC, jrose-r7 commented
@mrinehart-r7 can we ignore the 'no module named git' error here or no?

2021-11-02 15:51 UTC, pmara-r7 reviewed
2 nitpicks. Feel free to dismiss if you'd like and I'll circle back to re-approve

2021-11-02 15:51 UTC, pmara-r7 commented on workflows/Alert_on_InsightIDR_Multi_Country_Authentication/help.md
> +_There is no troubleshooting information at this time_
This could benefit from adding how to get the AD name from your group, but not necessary. If this is actually really complicated and a pain, respond here and I'll resolve the comment

2021-11-02 17:21 UTC, jrose-r7 commented on workflows/Alert_on_InsightIDR_Multi_Country_Authentication/help.md
> +* The ability to determine if a member of a certain user group is logged in from two or more countries
Good point. Updated Key features section to reflect this and added a bit more info

2021-11-02 17:22 UTC, jrose-r7 commented on workflows/Alert_on_InsightIDR_Multi_Country_Authentication/help.md
> +_There is no troubleshooting information at this time_
Do you mean linking documentation or writing it out - if the latter, that might be more complicated but lmk

2021-11-02 17:35 UTC, jrose-r7 commented
Not entirely sure why the WorkflowDescriptionValidator is reported as failing. Ran icon-validate again locally and got: 

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Executing validator WorkflowEncodingValidator
[*] Executing validator WorkflowParametersKeywordValidator
[*] Executing validator UseCaseValidator
[*] Executing validator UnapprovedKeywordsValidator
[*] Executing validator WorkflowPythonScriptUseValidator
[*] Workflow successfully validated!

2021-11-02 18:09 UTC, pmara-r7 commented on workflows/Alert_on_InsightIDR_Multi_Country_Authentication/help.md
> +_There is no troubleshooting information at this time_
I meant writing it out- if someone was to get this workflow, something that would tell them how to get the DN of the Group. So no problem if thats a bit complicated

2021-11-02 18:19 UTC, pmara-r7 commented
I also can't figure out why the workflow validator isn't picking up the description here- seems to be in fine. Might be a validator defect

2021-11-02 18:19 UTC, pmara-r7 submitted a review, later dismissed

2021-11-04 14:52 UTC, mrinehart-r7 requested changes

2021-11-04 14:52 UTC, mrinehart-r7 commented on workflows/Alert_on_InsightIDR_Multi_Country_Authentication/help.md
> +
```suggestion
* Access to InsightIDR
* IPStack API key

```

2021-11-04 14:52 UTC, mrinehart-r7 commented on workflows/Alert_on_InsightIDR_Multi_Country_Authentication/workflow.spec.yaml
> +products: ["insightconnect"]
```suggestion
products: ["insightconnect", "insightidr"]
```

2021-11-04 15:38 UTC, pmara-r7 approved these changes

2021-11-04 15:39 UTC, merged