New workflow cyber reason isolate with teams
rapid7/insightconnect-workflows pull request #484
Opened 2021-11-11 21:29 UTC by ewilson-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<Insert Workflow Image Here>

#### Job

<Insert Job Image Here>

#### Artifact

<Insert Artifact Image Here>
```

2021-11-12 17:33 UTC, mrinehart-r7 requested changes

2021-11-12 17:33 UTC, mrinehart-r7 commented on workflows/Isolate_Machine_with_Cybereason_from_Teams/Isolate_Machine_with_Cybereason_from_Teams.icon
> +              "description": "Slack user did not properly add username argument",
```suggestion
              "description": "Teams user did not properly add username argument",
```

2021-11-12 17:33 UTC, mrinehart-r7 commented on workflows/Isolate_Machine_with_Cybereason_from_Teams/Isolate_Machine_with_Cybereason_from_Teams.icon
> +              "description": "Slack user correctly entered arguments",
```suggestion
              "description": "Teams user correctly entered arguments",
```

2021-11-12 17:33 UTC, mrinehart-r7 approved these changes

2021-11-15 18:37 UTC, pmara-r7 approved these changes

2021-11-15 19:19 UTC, merged