MC-371 - Palo Alto Wildfire - Workflow Improvements
rapid7/insightconnect-workflows pull request #485
Opened 2021-11-30 23:47 UTC by dmandyna-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment
#### Icon-Validate

<details>

```
[*] Validating workflow at ./Office_365_Analysis_with_Palo_Alto_Wildfire/

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Executing validator WorkflowEncodingValidator
[*] Executing validator WorkflowParametersKeywordValidator
[*] Executing validator UseCaseValidator
[*] Executing validator UnapprovedKeywordsValidator
[*] Executing validator WorkflowPythonScriptUseValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 843.891ms
```

<summary>
icon-validate ./Office_365_Analysis_with_Palo_Alto_Wildfire/
</summary>
</details>

### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

![workflow_overview](https://user-images.githubusercontent.com/66844174/144145580-d9c3587f-3bdc-4578-a0ae-66f4fe855b13.png)

![workflow_analysis_loop](https://user-images.githubusercontent.com/66844174/144145600-da1cecdf-fa0c-4266-bcf2-8814444c6c6e.png)

![workflow_url_loop](https://user-images.githubusercontent.com/66844174/144145613-b4727a0a-c1c7-490d-b060-1228d483c26d.png)

![workflow_file_loop](https://user-images.githubusercontent.com/66844174/144145628-cf9a4914-86a1-449a-b651-611a8d005d4d.png)

![workflow_remediation_loop](https://user-images.githubusercontent.com/66844174/144145640-b56d3d8c-a043-4400-b1a1-0c145fa4e0aa.png)

#### Job

<img width="706" alt="jobs1" src="https://user-images.githubusercontent.com/66844174/144145955-b6d467ce-a788-45e4-8406-3f7b2c2cd4db.png">

<img width="1464" alt="job2" src="https://user-images.githubusercontent.com/66844174/144145988-ac71d18e-59bf-42be-86d5-945ca9f1d3b4.png">

#### Artifact

<img width="1444" alt="artifacts1" src="https://user-images.githubusercontent.com/66844174/144145656-49b6c942-9f1f-49d4-9633-a44d73961690.png">

<img width="1178" alt="artifacts2" src="https://user-images.githubusercontent.com/66844174/144145669-cbf09977-24dc-422f-b6c9-cb2bacdefe0b.png">

<img width="1441" alt="artifacts3" src="https://user-images.githubusercontent.com/66844174/144145676-44ac07c0-3110-4e0c-bee6-699cf7efc580.png">

2021-12-02 11:28 UTC, cmcnally-r7 submitted a review, later dismissed

2021-12-06 21:28 UTC, pmara-r7 commented on workflows/Office_365_Analysis_with_Palo_Alto_Wildfire/help.md
> +The remediation steps are disabled due to their destructive nature. To use them, they must be manually enabled after importing the workflow.
```suggestion
The remediation steps are disabled due to their destructive nature. To use them, they must be manually enabled after importing the workflow. To enable a step, hover your mouse over the step and click the icon to the left of the trash icon. 

```

2021-12-06 21:31 UTC, pmara-r7 commented on workflows/Office_365_Analysis_with_Palo_Alto_Wildfire/Office_365_Analysis_with_Palo_Alto_Wildfire.icon
> +                "content": "## Overview \n\n(This artifact should be removed)\n\nThis workflow assumes a standard phishing process. The user will push the phish button on a suspicious email that will
Should this be removed by us? This just seems like a description of the workflow

2021-12-07 17:57 UTC, mrinehart-r7 commented on workflows/Office_365_Analysis_with_Palo_Alto_Wildfire/Office_365_Analysis_with_Palo_Alto_Wildfire.icon
> +                "content": "## Overview \n\n(This artifact should be removed)\n\nThis workflow assumes a standard phishing process. The user will push the phish button on a suspicious email that will
Let's leave it here - it's sort of like a code comment for the user.

2021-12-07 18:20 UTC, mrinehart-r7 requested changes

2021-12-07 18:20 UTC, mrinehart-r7 commented on workflows/Office_365_Analysis_with_Palo_Alto_Wildfire/Office_365_Analysis_with_Palo_Alto_Wildfire.icon
> +                "content": "## Attached Email Analysis\n\n(This artifact can be removed) \n\nThis loop will analyze any each of the attached emails and look for any malicious indicators - these inclu
```suggestion
                "content": "## Attached Email Analysis\n\n(This artifact can be removed) \n\nThis loop will analyze any each of the attached emails and look for any malicious indicators - these include any malicious URLs found within these emails, any attached malicious files to these emails. These will be the best indicators of a suspicious email. If any are found this email will be marked as malicious. "
```

2021-12-07 18:20 UTC, mrinehart-r7 commented on workflows/Office_365_Analysis_with_Palo_Alto_Wildfire/help.md
> +API and account credentials for
```suggestion
API and account credentials for the following:

```

2021-12-07 18:20 UTC, mrinehart-r7 commented on workflows/Office_365_Analysis_with_Palo_Alto_Wildfire/help.md
> +|Microsoft Office 365 Email|5.1.0|1|
Any reason why we're using two different versions of the plugin? We should use a single version if possible.

2021-12-07 18:20 UTC, mrinehart-r7 commented on workflows/Office_365_Analysis_with_Palo_Alto_Wildfire/Office_365_Analysis_with_Palo_Alto_Wildfire.icon
> +            "name": "Sleep for 15",
```suggestion
            "name": "Sleep for 15 Seconds",
```
Clarifying the step intent

2021-12-11 14:37 UTC, dmandyna-r7 commented on workflows/Office_365_Analysis_with_Palo_Alto_Wildfire/help.md
> +|Microsoft Office 365 Email|5.1.0|1|
Yes, I've mentioned this a while ago to Claire on the Slack MoreSOAR chat when working on Office365 Workflow (pretty much the same workflow but uses VirusTotal instead of Palo Alto) - it seems that the trigger in the later versions is not working correctly. I've tried testing it with the latest, but the Workflow wouldn't trigger correctly.

2021-12-11 14:41 UTC, dmandyna-r7 commented on workflows/Office_365_Analysis_with_Palo_Alto_Wildfire/help.md
> +The remediation steps are disabled due to their destructive nature. To use them, they must be manually enabled after importing the workflow.
Hey @pmara-r7,
Thank you. Couple of months ago (maybe even longer) I was working on the Office365 workflow (it's very similar workflow as this one but utilises VirusTotal instead of Wildfire, and it also had these artefacts), and I've been told to leave them in place as it one of the starting workflows and the artefacts were there to inform the use of how the workflow is working. But if we prefer to get these removed I'll keep that in mind for the future :)

2022-01-10 22:22 UTC, mrinehart-r7 approved these changes

2022-01-11 16:24 UTC, blaxminarayan-r7 approved these changes

2022-01-11 16:26 UTC, merged