Enrich Indicators with IntSights from InsightIDR
rapid7/insightconnect-workflows pull request #489
Opened 2022-01-07 19:07 UTC by nhurd-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [x] Workflow verified as working in a test
- [x] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [x] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [x] Workflow includes a detailed Description
- [x] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [x] Triggers, Decisions, and other workflow steps include descriptions where needed
- [x] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [x] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [x] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [x] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

![WorkflowView1](https://user-images.githubusercontent.com/74786214/148594207-aacae6b7-b46b-4e92-8de3-37ff7877540d.png)
![WorkflowView2](https://user-images.githubusercontent.com/74786214/148594208-a640909d-4c44-4f13-8ffd-2f87553117e3.png)
![WorkflowView3](https://user-images.githubusercontent.com/74786214/148594209-90be1830-a15d-4929-9e44-c4c7351bbf9d.png)
![WorkflowView4](https://user-images.githubusercontent.com/74786214/148594210-a336782e-25d8-4abb-8090-f530547fe525.png)
![WorkflowView5](https://user-images.githubusercontent.com/74786214/148594211-06ecde04-a1a4-4b6f-8854-e8b4b7897d4f.png)

#### Job

Replaced with every permutation of Artifact screenshot instead

#### Artifact

![DomainLookupResults](https://user-images.githubusercontent.com/74786214/148594240-6d1cebf0-fc26-4493-9bf8-504561cec5af.png)
![HashLookupResults](https://user-images.githubusercontent.com/74786214/148594241-3c9f4b4d-2f02-4ee7-92d6-a4776413e549.png)
![IPLookupResults](https://user-images.githubusercontent.com/74786214/148594242-68daae82-6747-4a36-af82-078993cbf15f.png)
![URLLookupResults](https://user-images.githubusercontent.com/74786214/148594243-a743a0bd-3bff-473f-a717-9810e16164cd.png)

```

2022-01-07 19:22 UTC, pmara-r7 requested changes

2022-01-07 19:22 UTC, pmara-r7 commented on workflows/Enrich_Indicators_with_IntSights_from_InsightIDR/workflow.spec.yaml
> +  keywords: [Data Enrichment, Threat Detection & Response, Enrichment, Hash, URL, Domains, IP Address, Rapid7
```suggestion
  keywords: [Data Enrichment, Threat Detection & Response, Enrichment, Hash, URL, Domains, IP Address, Rapid7]
```

2022-01-07 19:25 UTC, pmara-r7 commented on workflows/Enrich_Indicators_with_IntSights_from_InsightIDR/workflow.spec.yaml
> +  keywords: [Data Enrichment, Threat Detection & Response, Enrichment, Hash, URL, Domains, IP Address, Rapid7]
```suggestion
  use_cases: [Data Enrichment, Thread Detection & Response]
  keywords: [Data Enrichment, Threat Detection & Response, Enrichment, Hash, URL, Domains, IP Address, Rapid7, parameters]
```

2022-01-07 19:27 UTC, pmara-r7 commented on workflows/Enrich_Indicators_with_IntSights_from_InsightIDR/workflow.spec.yaml
> +  use_cases: [Data Enrichment, Thread Detection & Response]
```suggestion
  use_cases: ['data_enrichment', 'threat_detection_and_response']
```

2022-03-16 13:45 UTC, blaxminarayan-r7 requested changes

2023-01-18 22:49 UTC, mcochran-r7 commented
closed due to age

2023-01-18 22:49 UTC, closed without merging