SOAR-8106 Update workflow tags
rapid7/insightconnect-workflows pull request #491
Opened 2022-01-26 19:18 UTC by tcheng-r7

Almost all workflows have had their use case tags updated in their workflow.spec.yaml. Additionally, separate hub tags for vendors and third-party products have been added.

All title and description attributes are also consistent with the use of double quotes.

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<Insert Workflow Image Here>

#### Job

<Insert Job Image Here>

#### Artifact

<Insert Artifact Image Here>
```

2022-01-26 21:12 UTC, mrinehart-r7 requested changes
Tagging in @chogan-r7 for some content questions and @tcheng-r7 for some slight fixes to the changes here.

2022-01-26 21:12 UTC, mrinehart-r7 commented on workflows/Create_BMC_Incident_for_Top_Remediations_from_InsightVM/workflow.spec.yaml
> +  keywords: []
@chogan-r7 do we want to add any keywords here?

2022-01-26 21:12 UTC, mrinehart-r7 commented on workflows/Create_Incident_in_ServiceNow_from_Slack/workflow.spec.yaml
> +  keywords: []
@chogan-r7 do we want to add any keywords here?

2022-01-26 21:12 UTC, mrinehart-r7 commented on workflows/Hello_IDR_Alert/workflow.spec.yaml
> +  vendors: []
@chogan-r7 This should include `rapid7` right?

2022-01-26 21:12 UTC, mrinehart-r7 commented on workflows/Hello_IDR_Alert/workflow.spec.yaml
> +  products: []
@chogan-r7 this should include `insightidr` right?

2022-01-26 21:12 UTC, mrinehart-r7 commented on workflows/InsightVM_Top_25_Remediations_to_JIRA/workflow.spec.yaml
> +  keywords: []
@chogan-r7 do we want to add any keywords here?

2022-01-26 21:12 UTC, mrinehart-r7 commented on workflows/InsightVM_Top_25_Remediations_to_Zendesk/workflow.spec.yaml
> +  keywords: []
@chogan-r7 do we want to add any keywords here?

2022-01-26 21:12 UTC, mrinehart-r7 commented on workflows/Quarantine_Endpoint_with_Broadcom_Symantec_Endpoint_Protection_from_Microsoft_Teams/workflow.spec.yaml
> +  Teams
```suggestion
title: "Quarantine Endpoint with Broadcom Symantec Endpoint Protection from Microsoft Teams"
```

2022-01-26 21:12 UTC, mrinehart-r7 commented on workflows/URLScan_with_Slack/workflow.spec.yaml
> +description: "This workflow enrichs a URL given via Slack command in urlscan.io and reports information back to Slack"
This should read `This workflow enriches ...`, fixing the typo in `enrichs`

2022-01-26 21:12 UTC, mrinehart-r7 commented on workflows/Virtually_Patch_Vulnerabilities_Found_by_InsightVM_with_Deep_Security/workflow.spec.yaml
> +    title: Report Artifact Sucessful Assignment of Multiple Rules
Can you fix the typo here in `Sucessful`? It should read `Successful`

2022-01-28 18:16 UTC, mrinehart-r7 submitted a review, later dismissed

2022-02-08 17:59 UTC, chogan-r7 commented on workflows/Create_Incident_in_ServiceNow_from_Slack/workflow.spec.yaml
> +  keywords: []
Nope idc that much about the keyword category

2022-02-08 17:59 UTC, chogan-r7 commented on workflows/Create_BMC_Incident_for_Top_Remediations_from_InsightVM/workflow.spec.yaml
> +  keywords: []
Nope idc that much about the keyword category

2022-02-08 18:00 UTC, chogan-r7 commented on workflows/Hello_IDR_Alert/workflow.spec.yaml
> +  vendors: []
yes good call

2022-02-08 18:01 UTC, chogan-r7 commented on workflows/Hello_IDR_Alert/workflow.spec.yaml
> +  products: []
yes perfect

2022-02-08 18:01 UTC, chogan-r7 commented on workflows/InsightVM_Top_25_Remediations_to_JIRA/workflow.spec.yaml
> +  keywords: []
no need!

2022-02-10 20:26 UTC, mrinehart-r7 approved these changes

2022-02-10 20:57 UTC, mberezin-r7 approved these changes

2022-02-11 15:47 UTC, merged