[MC-921] Update Check Host Block Status with Fortinet Firewall from Microsoft Teams workflow
rapid7/insightconnect-workflows pull request #494
Opened 2022-02-07 14:31 UTC by dsliwinski-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

<details>

```
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Executing validator WorkflowEncodingValidator
[*] Executing validator WorkflowParametersKeywordValidator
[*] Executing validator UseCaseValidator
[*] Executing validator UnapprovedKeywordsValidator
[*] Executing validator WorkflowPythonScriptUseValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 1537.3380000000002ms
```

<summary>
icon-validate .
</summary>
</details>

### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

![workflow](https://user-images.githubusercontent.com/73613193/152807473-1c9b1675-3741-4fa8-a9b4-737a95839d23.png)

#### Job

![check_block_status_domain](https://user-images.githubusercontent.com/73613193/152807502-db4756fd-62ef-4750-9814-a83eb50ccddc.png)
![check_block_status_ipv4](https://user-images.githubusercontent.com/73613193/152807512-a33e805f-ec01-4f30-9f94-2c217eadff24.png)
![check_block_status_ipv6](https://user-images.githubusercontent.com/73613193/152807522-907cb866-02bb-46d8-9352-a19767dfc02f.png)
![check_block_status_not_blocked](https://user-images.githubusercontent.com/73613193/152807534-fbe8f472-8da4-4b44-a808-eb1332be9cd8.png)

2022-02-16 00:46 UTC, r7-kszczepanskagorna approved these changes

2022-02-16 19:37 UTC, aholland-r7 reviewed
Merge conflicts need to be resolved, but otherwise approved

2022-02-25 15:01 UTC, aholland-r7 approved these changes

2022-02-28 12:43 UTC, igorski-r7 requested changes

2022-02-28 12:43 UTC, igorski-r7 commented on workflows/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams/Check_Host_Block_Status_with_Fortinet_Firewall_from_Microsoft_Teams.icon
> +              "Group Name": {
Where there is no added prefix IPv4 (same way as it's done in IPv6 Group Name)? Should that be better to leave that name without IPv4?
```suggestion
              "IPv4 Group Name": {
```

2022-02-28 12:59 UTC, llaszuk-r7 approved these changes

2022-02-28 13:03 UTC, merged