Initial workflow for Lookup Automox Host from Slack
rapid7/insightconnect-workflows pull request #496
Opened 2022-02-09 20:55 UTC by ax-zyoutz

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<Insert Workflow Image Here>

#### Job

<Insert Job Image Here>

#### Artifact

<Insert Artifact Image Here>
```

2022-02-10 03:39 UTC, ax-zyoutz commented
Workflow and job artifact screenshots:
<img width="594" alt="Screen Shot 2022-02-09 at 8 38 06 PM" src="https://user-images.githubusercontent.com/86067902/153332658-15ebd476-5818-402c-9923-00880ac570d8.png">
<img width="644" alt="Screen Shot 2022-02-09 at 8 37 38 PM" src="https://user-images.githubusercontent.com/86067902/153332662-844c068d-359b-47a5-8b86-5a4b085256ea.png">
<img width="627" alt="Screen Shot 2022-02-09 at 8 37 32 PM" src="https://user-images.githubusercontent.com/86067902/153332670-2d993cb0-0c4b-40da-bedb-1dbcee32d2ba.png">

Slack screenshots for found and not found host:
<img width="576" alt="Screen Shot 2022-02-09 at 8 37 16 PM" src="https://user-images.githubusercontent.com/86067902/153332735-641ce7f3-2249-42ad-baa3-3088fae5dfb7.png">
<img width="578" alt="Screen Shot 2022-02-09 at 8 36 47 PM" src="https://user-images.githubusercontent.com/86067902/153332740-c2c88489-8f85-4fba-b15d-3119bbcfac73.png">

2022-02-11 17:58 UTC, ax-zyoutz commented
@blaxminarayan-r7 Absolutely, will get the digits update right now for both slack and teas workflows. As for IPv4/IPv6 support, the endpoint in the action on returns IPv4 addresses at the moment. It's something we hope to follow up with in the future though, just no timeline on the API side yet.

2022-02-11 20:24 UTC, ax-zyoutz commented
@blaxminarayan-r7 Commit pushed and tested to refine the IPv4 regular expression with express number of digits

2022-02-14 16:21 UTC, blaxminarayan-r7 reviewed
Can you please include the workflow job/url in the slack message, so that you can refer back if needed.

2022-02-14 16:22 UTC, blaxminarayan-r7 requested changes
Kindly address the boolean validation and the workflow url

2022-02-14 17:38 UTC, blaxminarayan-r7 submitted a review, later dismissed

2022-02-14 18:46 UTC, mberezin-r7 submitted a review, later dismissed

2022-02-14 18:48 UTC, ax-zyoutz commented on workflows/Lookup_Automox_Host_From_Slack/help.md
> +* [Slack](https://insightconnect.help.rapid7.com/docs/configure-slack-for-chatops)
Oh, thanks Max. Didn't know there was a new page! Getting this committed now.

2022-02-14 18:50 UTC, mberezin-r7 approved these changes
Thanks Zac!

2022-02-14 19:27 UTC, blaxminarayan-r7 approved these changes

2022-02-14 19:27 UTC, merged