Initial workflow for Lookup Automox Host from Teams
rapid7/insightconnect-workflows pull request #497
Opened 2022-02-10 03:32 UTC by ax-zyoutz

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<Insert Workflow Image Here>

#### Job

<Insert Job Image Here>

#### Artifact

<Insert Artifact Image Here>
```

2022-02-10 03:35 UTC, ax-zyoutz commented
Screenshots of workflow and job output with a found and not found device:
<img width="376" alt="Screen Shot 2022-02-09 at 8 33 14 PM" src="https://user-images.githubusercontent.com/86067902/153332250-adcfd34e-c514-4567-b9e6-254f9e83980f.png">
<img width="632" alt="Screen Shot 2022-02-09 at 8 33 31 PM" src="https://user-images.githubusercontent.com/86067902/153332256-21602e8a-883c-4c81-9576-cf154085f571.png">
<img width="626" alt="Screen Shot 2022-02-09 at 8 33 46 PM" src="https://user-images.githubusercontent.com/86067902/153332261-a2be7ea7-30ff-4a21-9e4e-355b4b3e67a8.png">

Teams threads:
<img width="984" alt="Screen Shot 2022-02-09 at 8 34 42 PM" src="https://user-images.githubusercontent.com/86067902/153332402-c54bf2d4-e19d-4175-bc20-135b333b82e1.png">
<img width="995" alt="Screen Shot 2022-02-09 at 8 34 47 PM" src="https://user-images.githubusercontent.com/86067902/153332411-7abc4f51-a342-4b7b-92a2-060b62f961e6.png">

2022-02-11 05:26 UTC, ax-zyoutz commented on workflows/Lookup_Automox_Host_From_Teams/help.md
> +There are two workflow parameters you will need to configure in order to complete setup of your workflow:
```suggestion
There are three workflow parameters you will need to configure in order to complete setup of your workflow:
```

2022-02-11 20:25 UTC, ax-zyoutz commented
@blaxminarayan-r7 Commit pushed and tested to refine the IPv4 regular expression with express number of digits

2022-02-14 17:42 UTC, ax-zyoutz commented on workflows/Lookup_Automox_Host_From_Teams/Lookup_Automox_Host_From_Teams.icon
> +            "identifier": "send_html_message",
Changed to `send_html_message` here so we can include workflow job url the same as a host found message

2022-02-14 17:49 UTC, mrinehart-r7 requested changes

2022-02-14 17:49 UTC, mrinehart-r7 commented on workflows/Lookup_Automox_Host_From_Teams/help.md
> +* InsightConnect License
```suggestion
* InsightConnect license
```

2022-02-14 17:49 UTC, mrinehart-r7 requested changes

2022-02-14 17:49 UTC, mrinehart-r7 commented on workflows/Lookup_Automox_Host_From_Teams/help.md
> +* Automox API Key
```suggestion
* Automox API key
```

2022-02-14 22:33 UTC, mrinehart-r7 approved these changes

2022-02-14 23:13 UTC, blaxminarayan-r7 approved these changes

2022-02-14 23:13 UTC, merged