MC-603 Create Enrich Indicator with Recorded Future to Slack workflow
rapid7/insightconnect-workflows pull request #520
Opened 2022-03-31 11:11 UTC by mgrandys-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

<details>

```
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Executing validator WorkflowEncodingValidator
[*] Executing validator WorkflowParametersKeywordValidator
[*] Executing validator WorkflowUseCaseValidator
[*] Executing validator UnapprovedKeywordsValidator
[*] Executing validator WorkflowPythonScriptUseValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 1567.801ms
```

<summary>
icon-validate --all .
</summary>
</details>

### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

![Workflow](https://user-images.githubusercontent.com/98016184/161041881-4242a59e-641a-408d-859b-86178a73a692.png)

![Workflow_Addresses_Loop](https://user-images.githubusercontent.com/98016184/161041910-3c64c7e4-7569-4d7d-9449-2058a5d7bd6b.png)

![Workflow_Domains_Loop](https://user-images.githubusercontent.com/98016184/161041915-7ae56b18-3ccb-4b69-8e79-46d31948a5c7.png)

![Workflow_Hashes_Loop](https://user-images.githubusercontent.com/98016184/161041918-48c4f004-f3a6-4595-991b-aedcefed43d5.png)

![Workflow_Processes_Loop](https://user-images.githubusercontent.com/98016184/161041923-d81883d9-caba-4ed8-80ed-eb2b8afa8335.png)

![Workflow_URLs_Loop](https://user-images.githubusercontent.com/98016184/161041925-24f5378e-2549-4a5d-945f-6ea9dee1a39f.png)

#### Job

<img width="1208" alt="Screenshot 2022-03-31 at 12 10 43" src="https://user-images.githubusercontent.com/98016184/161042287-4ffef802-c078-4157-b1b3-56261befa853.png">

#### Artifact

![Recorded_Future_Domain_Lookup_Output](https://user-images.githubusercontent.com/98016184/161042041-2cb63306-06b9-4a95-bf9c-f41783742a8f.png)

![Recorded_Future_Hash_Lookup_Output](https://user-images.githubusercontent.com/98016184/161042047-71e3a6a6-61f9-458e-8c5c-166e55cfd8a3.png)

![Recorded_Future_IP_Lookup_Output](https://user-images.githubusercontent.com/98016184/161042048-68fecb22-1a98-4f97-a715-86174fb25617.png)

![Recorded_Future_URL_Lookup_Output_2](https://user-images.githubusercontent.com/98016184/161042051-3f9bec8e-731e-4184-9837-a57a1128b799.png)

![Recorded_Future_URL_Lookup_Output](https://user-images.githubusercontent.com/98016184/161042055-a1295ef9-238f-4bad-bfcb-0985f8e0b957.png)

#### Slack
<img width="746" alt="Slack_Domain_Lookup" src="https://user-images.githubusercontent.com/98016184/161042140-56b0aaa9-6140-437d-946a-f97f64aba368.png">
<img width="734" alt="Slack_Hash_Lookup" src="https://user-images.githubusercontent.com/98016184/161042149-4acc10e0-20e3-489e-9a25-d69204a2c73b.png">
<img width="445" alt="Slack_IP_Lookup" src="https://user-images.githubusercontent.com/98016184/161042153-451ea28e-29d1-4ca4-bbcf-a17ff027c996.png">
<img width="747" alt="Slack_URL_Lookup" src="https://user-images.githubusercontent.com/98016184/161042158-c7c32022-80f8-498e-a64b-576f70b1cfb7.png">

2022-03-31 11:11 UTC, mgrandys-r7 commented
Job:
https://us.connect.insight.rapid7.com/99AD7AE6317E5DAEB626#/jobs/details/dbef97f2-7764-460f-9dda-9d89bd356b76

2022-04-04 10:56 UTC, dsliwinski-r7 requested changes

2022-04-04 10:56 UTC, dsliwinski-r7 commented on workflows/Enrich_Indicators_with_Recorded_Future_from_IDR_Alert_to_Slack/Enrich_Indicators_with_Recorded_Future_from_IDR_Alert_to_Slack.icon
> +{
@mgrandys-r7 The `Any Reports to Send?` step will cause the workflow to fail if the alert does not contain all types of indicators (i.e. in the case of most alerts). Sending all reports in one message will result in incomplete reports due to the character limit. It is worth adding a step that will send information about the alert itself, as it is in the `IDR Alert Input Summary` step. I think it would be a better solution to send separate messages with the report for each indicator.

2022-04-04 10:56 UTC, dsliwinski-r7 commented on workflows/Enrich_Indicators_with_Recorded_Future_from_IDR_Alert_to_Slack/help.md
> +* Recorded Future API Key and Account Credentials
```suggestion
* InsightConnect License
* Recorded Future API Key and Account Credentials
* [Slack](https://insightconnect.help.rapid7.com/docs/configure-slack-for-chatops)
```

2022-04-04 10:56 UTC, dsliwinski-r7 commented on workflows/Enrich_Indicators_with_Recorded_Future_from_IDR_Alert_to_Slack/help.md
> +* While Selecting Alerts, check any alerts you would like to automatically enrich
This section needs to be updated as the instructions provided are invalid. Workflow does not use the Cb Response plugin, the workflow name is incorrect and there is no information about the parameters to be configured.

2022-04-04 10:56 UTC, dsliwinski-r7 commented on workflows/Enrich_Indicators_with_Recorded_Future_from_IDR_Alert_to_Slack/help.md
> +
Could you please add a `Usage` section?

2022-04-04 10:56 UTC, dsliwinski-r7 commented on workflows/Enrich_Indicators_with_Recorded_Future_from_IDR_Alert_to_Slack/help.md
> +* [Recorded Future API Documentation](https://support.recordedfuture.com/hc/en-us/categories/115000803507-Raw-API)
```suggestion
* [Recorded Future API Documentation](https://support.recordedfuture.com/hc/en-us/categories/115000803507-Raw-API)
* [Slack](https://slack.com/)
```

2022-04-06 08:28 UTC, mgrandys-r7 commented
Workflow and job after PR changes

Workflow:
https://us.connect.insight.rapid7.com/99AD7AE6317E5DAEB626#/workflows/details/ef5e888a-cb32-4b5b-89cd-b82f7bae2391/versions/9d23c14d-ae37-494b-9079-caf4db1b68b6

Job:
https://us.connect.insight.rapid7.com/99AD7AE6317E5DAEB626#/jobs/details/663f24a4-f1bf-4f91-b7dd-a8ca4206c8c4

2022-04-11 10:09 UTC, dsliwinski-r7 approved these changes

2022-04-12 21:20 UTC, r7-kszczepanskagorna approved these changes

2022-05-11 13:23 UTC, igorski-r7 approved these changes

2022-05-19 15:07 UTC, merged