MC-864 - Update ServiceNow Plugin in Create incident in ServiceNow from Slack Workflow
rapid7/insightconnect-workflows pull request #521
Opened 2022-04-10 19:03 UTC by dmandyna-r7

## Requirements

[MC-864](https://issues.corp.rapid7.com/browse/MC-864)

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

#### Icon-Validate

<details>

```
[*] Validating workflow at ./Create_Incident_in_ServiceNow_from_Slack/

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Executing validator WorkflowEncodingValidator
[*] Executing validator WorkflowParametersKeywordValidator
[*] Executing validator WorkflowUseCaseValidator
[*] Executing validator UnapprovedKeywordsValidator
[*] Executing validator WorkflowPythonScriptUseValidator
        Python 3 Script use found in these steps
                [-] Step Name - Parse Incident Parameters
        Please review these steps carefully before use
[*] Workflow successfully validated!

----
[*] Total time elapsed: 1685.961ms
```

<summary>
icon-validate ./Create_Incident_in_ServiceNow_from_Slack/
</summary>
</details>

### Screenshots

#### Workflow Builder

<img width="454" alt="workflow" src="https://user-images.githubusercontent.com/66844174/162635357-0a648839-b8ad-4b2b-8558-296317a5d7be.png">

#### Job

<img width="1840" alt="InsightConnect 2022-04-10 20-28-55" src="https://user-images.githubusercontent.com/66844174/162635379-2f6e61d9-8e2f-4986-8e50-114c938eb77a.png">

#### Artifact

<img width="621" alt="successful_artifact" src="https://user-images.githubusercontent.com/66844174/162635399-effd198b-d9ee-4969-8f03-3b21f125a02d.png">

2022-04-12 08:19 UTC, mgrandys-r7 submitted a review, later dismissed

2022-04-12 08:19 UTC, mgrandys-r7 commented on workflows/Create_Incident_in_ServiceNow_from_Slack/workflow.spec.yaml
> +  keywords: [itsm, parameters]
```suggestion
  keywords: [itsm, parameters, slack, servicenow]
```

2022-04-12 10:46 UTC, dsliwinski-r7 approved these changes

2022-04-13 19:04 UTC, dmandyna-r7 commented
Updated icon-validate after commit suggestions:
```
[*] Validating workflow at ./Create_Incident_in_ServiceNow_from_Slack

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Executing validator WorkflowEncodingValidator
[*] Executing validator WorkflowParametersKeywordValidator
[*] Executing validator WorkflowUseCaseValidator
[*] Executing validator UnapprovedKeywordsValidator
[*] Executing validator WorkflowPythonScriptUseValidator
        Python 3 Script use found in these steps
                [-] Step Name - Parse Incident Parameters
        Please review these steps carefully before use
[*] Workflow successfully validated!

----
[*] Total time elapsed: 1393.6660000000002ms
```

2022-04-15 21:30 UTC, dsliwinski-r7 approved these changes

2022-06-08 14:23 UTC, llaszuk-r7 requested changes
Left comment, please fix validator

2022-06-08 14:23 UTC, llaszuk-r7 commented on workflows/Create_Incident_in_ServiceNow_from_Slack/Create_Incident_in_ServiceNow_from_Slack.icon
> +        "description": "# Description\n\nCreate a ServiceNow Incident directly from Slack. If your team is collaborating on and handling Incidents in Slack you can now send the information you need t
I think that's why validator failing, version of Python 3 Script and ServiceNow don't coincide like in help.md

2022-06-17 17:44 UTC, dmandyna-r7 commented on workflows/Create_Incident_in_ServiceNow_from_Slack/Create_Incident_in_ServiceNow_from_Slack.icon
> +        "description": "# Description\n\nCreate a ServiceNow Incident directly from Slack. If your team is collaborating on and handling Incidents in Slack you can now send the information you need t
Hey @llaszuk-r7,

This change is generated by make regenerate on the plugin, it adds content of the help.md file to description of the workflow. I can revert that change if you like. 

Regarding the validator, it's failing for the same reason on the master branch. It's because the workflow uses the Python3 script within in - it's not caused by my change (MC-864). If you like I can raise this issue and get a ticket created to re-work the workflow to get rid of that Python3 step, please let me know.

2022-11-29 22:01 UTC, merged