[MC-658] New workflow - Check Host Quarantine Status in FireEye HX from Microsoft Teams
rapid7/insightconnect-workflows pull request #526
Opened 2022-05-12 10:11 UTC by dsliwinski-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

<details>

```
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Executing validator WorkflowEncodingValidator
[*] Executing validator WorkflowParametersKeywordValidator
[*] Executing validator WorkflowUseCaseValidator
[*] Executing validator UnapprovedKeywordsValidator
[*] Executing validator WorkflowPythonScriptUseValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 3152.168ms
```

<summary>
icon-validate .
</summary>
</details>

### Screenshots

#### Workflow Builder

![workflow](https://user-images.githubusercontent.com/73613193/168047460-458ec9af-0174-4cba-a546-477ffdd635dc.png)

#### Job

![check_status_contained](https://user-images.githubusercontent.com/73613193/168047501-137f2790-f568-4557-b1a6-fae819a61d1c.png)
![check_status_normal](https://user-images.githubusercontent.com/73613193/168047515-3ea30b7d-a7de-4668-b2d5-c0c79df4e42f.png)
![host_not_found](https://user-images.githubusercontent.com/73613193/168047541-92a9a58d-0f49-4bee-83e5-e6e04bd60617.png)
![host_not_provided](https://user-images.githubusercontent.com/73613193/168047563-782a4486-3845-4b59-8c27-b5d8699d4271.png)

2022-05-20 08:56 UTC, mgrandys-r7 submitted a review, later dismissed

2022-06-13 17:25 UTC, dmandyna-r7 requested changes
Looks good after fixing the wording in help.md.

2022-06-13 17:25 UTC, dmandyna-r7 commented on workflows/Check_Host_Quarantine_Status_in_FireEye_HX_from_Microsoft_Teams/help.md
> +There are two parameters you will need to configure in order to complete setup of your workflow:
```suggestion
There are two parameters you will need to be configured in order to complete setup of your workflow:
```

2022-06-13 17:25 UTC, dmandyna-r7 commented on workflows/Check_Host_Quarantine_Status_in_FireEye_HX_from_Microsoft_Teams/help.md
> +* Team Name: The Microsoft Teams team name in your environment where the workflow should be triggered and respond
```suggestion
* Team Name: The Microsoft Teams team name in your environment where the workflow should be triggered from and where it responds to
```

2022-06-13 17:25 UTC, dmandyna-r7 commented on workflows/Check_Host_Quarantine_Status_in_FireEye_HX_from_Microsoft_Teams/help.md
> +* Channel Name: The Microsoft Teams channel name in your environment where the workflow should be triggered and respond (the channel should exist in the aforementioned team)
```suggestion
* Channel Name: The Microsoft Teams channel name in your environment where the workflow should be triggered from and where responds to (the channel should exist in the aforementioned team)
```

2022-06-15 06:54 UTC, mgrandys-r7 approved these changes

2022-11-29 22:00 UTC, merged