[MC-613] Update Alert on New High Risk Vulnerability in InsightVM with Slack workflow
rapid7/insightconnect-workflows pull request #533
Opened 2022-06-17 12:39 UTC by dsliwinski-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

## Assessment

<details>

```
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Executing validator WorkflowEncodingValidator
[*] Executing validator WorkflowParametersKeywordValidator
[*] Executing validator WorkflowUseCaseValidator
[*] Executing validator UnapprovedKeywordsValidator
[*] Executing validator WorkflowPythonScriptUseValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 2853.3379999999997ms
```

<summary>
icon-validate .
</summary>
</details>

### Screenshots

#### Workflow Builder

![workflow1](https://user-images.githubusercontent.com/73613193/174299836-890a8cd8-cd3c-42f5-8cac-9e872f0b5bd7.png)
![workflow2](https://user-images.githubusercontent.com/73613193/174299844-1051e3c8-4712-4a0a-8f9a-426c9e9fa458.png)

#### Job

![slack_output](https://user-images.githubusercontent.com/73613193/174299858-5625fa45-134b-4fb1-b700-e26a8c8fa44b.png)

2022-06-20 12:36 UTC, mgrandys-r7 requested changes

2022-06-20 12:36 UTC, mgrandys-r7 commented on workflows/Alert_on_New_High_Risk_Vulnerability_in_InsightVM_with_Slack/Alert_on_New_High_Risk_Vulnerability_in_InsightVM_with_Slack.icon
> +        "description": "# Description\n\nThis workflow listens for InsightVM Webhook Events for newly discovered vulnerabilities, checks the CVSS score of each new vulnerability, and posts notificati
You should replace `Microsoft Teams` with `Slack` as this workflow sends alert to Slack chanel

2022-06-21 10:27 UTC, mgrandys-r7 approved these changes

2022-06-21 15:40 UTC, igorski-r7 approved these changes

2022-06-21 15:42 UTC, mberezin-r7 approved these changes

2022-06-23 14:48 UTC, merged