[MC-1236] Update ServiceNow plugin in workflows
rapid7/insightconnect-workflows pull request #534
Opened 2022-06-27 11:41 UTC by dsliwinski-r7

Workflows:

- Open Tickets in ServiceNow for Newly Discovered Vulns
- Close Tickets in ServiceNow for Newly Remediated Vulnerabilities

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Open Tickets in ServiceNow for Newly Discovered Vulns

<details>

```
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Executing validator WorkflowEncodingValidator
[*] Executing validator WorkflowParametersKeywordValidator
[*] Executing validator WorkflowUseCaseValidator
[*] Executing validator UnapprovedKeywordsValidator
[*] Executing validator WorkflowPythonScriptUseValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 3276.874ms
```

<summary>
icon-validate .
</summary>
</details>

Close Tickets in ServiceNow for Newly Remediated Vulnerabilities

<details>

```
[*] Validating workflow at .

[*] Running Integration Validators...
[*] Executing validator WorkflowDirectoryNameMatchValidator
[*] Executing validator WorkflowFilesValidator
[*] Executing validator WorkflowHelpValidator
[*] Executing validator WorkflowChangelogValidator
[*] Executing validator WorkflowVendorValidator
[*] Executing validator WorkflowVersionValidator
[*] Executing validator WorkflowExtensionValidator
[*] Executing validator WorkflowSupportValidator
[*] Executing validator WorkflowPNGHashValidator
[*] Executing validator WorkflowICONFileNameValidator
[*] Executing validator WorkflowScreenshotValidator
[*] Executing validator WorkflowTitleValidator
[*] Executing validator WorkflowDescriptionValidator
[*] Executing validator WorkflowNameValidator
[*] Executing validator WorkflowProfanityValidator
[*] Executing validator WorkflowHelpPluginUtilizationValidator
[*] Executing validator WorkflowICONFileValidator
[*] Executing validator WorkflowEncodingValidator
[*] Executing validator WorkflowParametersKeywordValidator
[*] Executing validator WorkflowUseCaseValidator
[*] Executing validator UnapprovedKeywordsValidator
[*] Executing validator WorkflowPythonScriptUseValidator
[*] Workflow successfully validated!

----
[*] Total time elapsed: 2896.077ms
```

<summary>
icon-validate .
</summary>
</details>

### Screenshots

#### Job

Open Tickets in ServiceNow for Newly Discovered Vulns

![job_open](https://user-images.githubusercontent.com/73613193/175932915-9681cd9e-6754-4a18-ad69-a9f3a6b85eff.png)

Close Tickets in ServiceNow for Newly Remediated Vulnerabilities

![job_close](https://user-images.githubusercontent.com/73613193/175932933-66bbc75e-4d1d-409a-9194-64bd94e8c2f0.png)

#### Artifact

Open Tickets in ServiceNow for Newly Discovered Vulns

<img width="1241" alt="artifact_open" src="https://user-images.githubusercontent.com/73613193/175932956-e26927be-8fb0-49a9-9339-aac43b26ff45.png">

Close Tickets in ServiceNow for Newly Remediated Vulnerabilities

<img width="1226" alt="artifact_close" src="https://user-images.githubusercontent.com/73613193/175933215-c1b9e94c-1de3-488e-9237-1d8d0a64c2cc.png">

2022-06-27 22:23 UTC, dmandyna-r7 reviewed
Just one comment, other than that it looks good.

2022-07-04 15:23 UTC, dmandyna-r7 approved these changes

2022-07-06 10:09 UTC, mgrandys-r7 requested changes

2022-07-07 07:35 UTC, mgrandys-r7 approved these changes

2022-08-25 20:55 UTC, dmandyna-r7 approved these changes

2022-11-29 22:01 UTC, merged