Update unshorten url with slack
rapid7/insightconnect-workflows pull request #544
Opened 2022-10-18 18:32 UTC by mcochran-r7

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<Insert Workflow Image Here>

#### Job

<Insert Job Image Here>

#### Artifact

<Insert Artifact Image Here>
```

2022-10-24 21:03 UTC, sengleson-r7 requested changes
Two change requests:
1. Replace the "http://rapid7.com" links with the actual variables from the workflow. I am not sure if it is possible, but if we can _not_ hyperlink that may be best, seeing as these may be malicious URLs in the real world!
2. Add a link to the Job in the confirmation message

2022-10-24 21:03 UTC, sengleson-r7 commented on workflows/Unshorten_URL_with_Slack/Unshorten_URL_with_Slack.icon
>                  "message": ":notebook_with_decorative_cover: URL Unshorten for <http://rapid7.com|{{[6f80dc1f-9a48-4fbd-bfa0-06f2a86a6c04].[content]}}> :notebook_with_decorative_cover:\n_WhoIs_\n> Sh
We have the wrong variables and hyperlinks here! All these are configured to go to "http://rapid7.com" =)

2022-11-28 18:27 UTC, mcochran-r7 commented on workflows/Unshorten_URL_with_Slack/Unshorten_URL_with_Slack.icon
>                  "message": ":notebook_with_decorative_cover: URL Unshorten for <http://rapid7.com|{{[6f80dc1f-9a48-4fbd-bfa0-06f2a86a6c04].[content]}}> :notebook_with_decorative_cover:\n_WhoIs_\n> Sh
This should be fixed now

2022-11-28 18:27 UTC, mcochran-r7 commented
Changes made workflow should be ready for review

2022-11-29 19:05 UTC, ewilson-r7 approved these changes
Ran through a couple of tests in Anonymoose

2022-11-30 00:54 UTC, sengleson-r7 approved these changes

2022-11-30 00:55 UTC, merged