Updated Microsoft-Office-365-Email-Indicators-to-Slack
rapid7/insightconnect-workflows pull request #558
Opened 2022-12-09 16:13 UTC by mcochran-r7

Updated plugin versions replaced Python with Type Converter, added parameters

## Requirements

Workflow contributors, verify you have completed the following items by checking them off:

### Checklist
- [ ] Workflow verified as working in a test
- [ ] Workflow bundle includes `Name_of_Workflow.icon` file, `help.md` file, `workflow.spec.yaml` file, and `screenshots` directory
- [ ] Workflow title should follow general [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Workflow includes a detailed Description
- [ ] Workflow step names follow [Title of Articles](http://grammar.yourdictionary.com/capitalization/rules-for-capitalization-in-titles.html) format
- [ ] Triggers, Decisions, and other workflow steps include descriptions where needed
- [ ] Workflow includes at least one `Final Report` artifact that summarizes workflow execution details
- [ ] Workflow bundle (directory) is named after the title of the workflow in snake case with first letters capitalized, e.g. `workflows/Name_of_Workflow/`
- [ ] `help.md` file includes Description, Key Features, Requirements, Setup, Technical Details, Version History, and References
- [ ] `workflow.spec.yaml` file includes `products`, `name`, `title`, `description`, `use_cases` tags, `keywords` tags, `source_url`, and the `name` for each screenshot matches a PNG image in the `screenshots` directory

### Assessment

Post your results with screenshots in this PR using the following style:

```
### Screenshots

Screenshots help your reviewers provide valuable feedback on your contribution. To add a screenshot here, simply drag and drop the PNG files from a file explorer.

#### Workflow Builder

<Insert Workflow Image Here>

#### Job

<Insert Job Image Here>

#### Artifact

<Insert Artifact Image Here>
```

2022-12-09 16:14 UTC, mcochran-r7 commented
Working version in SimLab (https://us.connect.insight.rapid7.com/7F913342E90748B5F07A#/workflows/details/4ea5604b-9790-479c-b436-e79c5d1b5a68/versions/dbca436e-f175-4e31-b559-4651c51ffb1d)

2022-12-13 14:32 UTC, ewilson-r7 requested changes

2022-12-13 14:32 UTC, ewilson-r7 commented on workflows/Microsoft_Office_365_Email_Indicators_to_Slack/Microsoft_Office_365_Email_Indicators_to_Slack.icon
> +                "subject_query": "Update Test Slack"
Probably want to remove the Subject Query for the mailbox trigger here

2022-12-13 15:33 UTC, mcochran-r7 commented on workflows/Microsoft_Office_365_Email_Indicators_to_Slack/Microsoft_Office_365_Email_Indicators_to_Slack.icon
> +                "subject_query": "Update Test Slack"
Removed and updated

2022-12-13 15:37 UTC, ewilson-r7 approved these changes
Good to go

2022-12-13 15:43 UTC, merged